-- ============================================================
--  QSToolkit V1.10 — Exam Questions Seed Data
--  105 factually accurate questions across 6 categories
-- ============================================================

INSERT INTO exam_questions (exam_category, exam_name, topic, question_text, question_type, options, correct_answer, explanation, difficulty, year, university, course_code, tags) VALUES

-- ============================================================
-- CATEGORY 1: NIQS PROBATION EXAM (15 questions)
-- ============================================================
('nigerian_professional', 'NIQS Probation Exam', 'Measurement Basics', 'What does SMM7 stand for in the context of quantity surveying measurement?', 'mcq', '[{"label":"A","text":"Standard Measurement Manual 7th Edition"},{"label":"B","text":"Standard Method of Measurement, 7th Edition"},{"label":"C","text":"Surveying and Measurement Manual 7"},{"label":"D","text":"Standard Manual for Measurement 7"}]', 'B', 'SMM7 stands for Standard Method of Measurement, 7th Edition. It is the traditional measurement standard for building works adopted in Nigeria from British practice.', 'easy', NULL, NULL, NULL, ARRAY['measurement','smm7','niqs','probation']),

('nigerian_professional', 'NIQS Probation Exam', 'Materials of Construction', 'The standard size of a sandcrete block commonly used in Nigeria is:', 'mcq', '[{"label":"A","text":"400mm × 200mm × 100mm"},{"label":"B","text":"450mm × 225mm × 200mm"},{"label":"C","text":"450mm × 225mm × 150mm (9-inch)"},{"label":"D","text":"500mm × 250mm × 150mm"}]', 'C', 'The standard sandcrete block size in Nigeria is 450mm × 225mm × 150mm (commonly called 9-inch block). The 6-inch block is 450mm × 225mm × 150mm.', 'easy', NULL, NULL, NULL, ARRAY['materials','blocks','sandcrete','nigeria']),

('nigerian_professional', 'NIQS Probation Exam', 'Concrete Technology', 'The dry volume factor used to convert wet volume of concrete to dry volume is:', 'mcq', '[{"label":"A","text":"1.25"},{"label":"B","text":"1.44"},{"label":"C","text":"1.54"},{"label":"D","text":"1.75"}]', 'C', 'The dry volume factor for concrete is 1.54. Dry volume = Wet volume × 1.54. This accounts for the voids between dry materials before water is added.', 'medium', NULL, NULL, NULL, ARRAY['concrete','volume','calculation','mix']),

('nigerian_professional', 'NIQS Probation Exam', 'Concrete Technology', 'For a 1:2:4 concrete mix ratio, approximately how many bags of cement (50kg each) are required for 1m³ of concrete?', 'mcq', '[{"label":"A","text":"4 bags"},{"label":"B","text":"5 bags"},{"label":"C","text":"6 bags"},{"label":"D","text":"8 bags"}]', 'C', 'For 1:2:4 mix: Dry volume = 1 × 1.54 = 1.54m³. Cement proportion = 1.54 / (1+2+4) × 1 = 0.22m³. Each 50kg bag ≈ 0.0347m³. Bags = 0.22 / 0.0347 ≈ 6.3 bags, commonly taken as 6 bags.', 'medium', NULL, NULL, NULL, ARRAY['concrete','cement','mix','calculation']),

('nigerian_professional', 'NIQS Probation Exam', 'Basic QS Duties', 'Which of the following is NOT a primary function of a Quantity Surveyor?', 'mcq', '[{"label":"A","text":"Preparation of bills of quantities"},{"label":"B","text":"Valuation of construction works"},{"label":"C","text":"Structural design of buildings"},{"label":"D","text":"Cost consultancy and financial advisory"}]', 'C', 'Structural design is the responsibility of a Structural Engineer, not a Quantity Surveyor. A QS focuses on cost management, measurement, valuation, and financial advisory in construction.', 'easy', NULL, NULL, NULL, ARRAY['professional','duties','roles','ethics']),

('nigerian_professional', 'NIQS Probation Exam', 'Plastering and Finishes', 'The standard plastering mix ratio (cement to sand) commonly used in Nigeria is:', 'mcq', '[{"label":"A","text":"1:2"},{"label":"B","text":"1:3"},{"label":"C","text":"1:4"},{"label":"D","text":"1:6"}]', 'C', 'The standard plastering mix ratio in Nigeria is 1:4 (cement to sand). The standard thickness of plastering is 15mm on walls.', 'easy', NULL, NULL, NULL, ARRAY['plastering','finishes','mix','materials']),

('nigerian_professional', 'NIQS Probation Exam', 'Steel Reinforcement', 'The standard grade of steel reinforcement used for concrete structures in Nigeria is:', 'mcq', '[{"label":"A","text":"BS 4449 Grade 250"},{"label":"B","text":"BS 4449 Grade 460"},{"label":"C","text":"BS 4449 Grade 600"},{"label":"D","text":"ASTM A615 Grade 40"}]', 'B', 'BS 4449 Grade 460 is the standard high-yield steel reinforcement grade used in Nigerian construction. The "460" refers to the minimum yield strength of 460 N/mm².', 'medium', NULL, NULL, NULL, ARRAY['steel','reinforcement','bs4449','materials']),

('nigerian_professional', 'NIQS Probation Exam', 'Earthwork', 'The bulking factor for laterite soil commonly used in Nigerian construction is:', 'mcq', '[{"label":"A","text":"1.10"},{"label":"B","text":"1.25"},{"label":"C","text":"1.35"},{"label":"D","text":"1.50"}]', 'C', 'The bulking factor for laterite soil is 1.35. This means 1m³ of compacted laterite becomes 1.35m³ when excavated and loose. Other factors: Clay = 1.25, Loam = 1.20, Sandy soil = 1.10.', 'medium', NULL, NULL, NULL, ARRAY['earthwork','excavation','laterite','bulking']),

('nigerian_professional', 'NIQS Probation Exam', 'Roofing', 'The effective coverage of a standard longspan aluminium roofing sheet (3.6m × 0.9m) in Nigeria is approximately:', 'mcq', '[{"label":"A","text":"2.50 m²"},{"label":"B","text":"3.24 m²"},{"label":"C","text":"3.60 m²"},{"label":"D","text":"4.00 m²"}]', 'B', 'A standard longspan aluminium sheet measures 3.6m × 0.9m = 3.24 m². This is the effective coverage after accounting for side laps. Allow 10-15% waste for gable roofs, 15-20% for hipped roofs.', 'easy', NULL, NULL, NULL, ARRAY['roofing','aluminium','coverage','materials']),

('nigerian_professional', 'NIQS Probation Exam', 'Professional Practice', 'Which of the following documents is NOT typically part of the contract documents in Nigerian construction?', 'mcq', '[{"label":"A","text":"Bill of Quantities"},{"label":"B","text":"Conditions of Contract"},{"label":"C","text":"Architect''s personal diary"},{"label":"D","text":"Drawings"}]', 'C', 'The Architect''s personal diary is not a contract document. Contract documents typically include: the agreement/conditions of contract, specifications, drawings, bill of quantities, and any addenda.', 'easy', NULL, NULL, NULL, ARRAY['professional','contract','practice','documents']),

('nigerian_professional', 'NIQS Probation Exam', 'Concrete Technology', 'For a 1:3:6 concrete mix, the approximate number of cement bags (50kg) required per cubic metre of concrete is:', 'mcq', '[{"label":"A","text":"3 bags"},{"label":"B","text":"4 bags"},{"label":"C","text":"5 bags"},{"label":"D","text":"6 bags"}]', 'B', 'For 1:3:6 mix: Dry volume = 1.54m³. Cement = 1.54 / (1+3+6) × 1 = 0.154m³. Bags = 0.154 / 0.0347 ≈ 4.4 bags, commonly taken as 4 bags. This is a leaner mix used for foundations and mass concrete.', 'medium', NULL, NULL, NULL, ARRAY['concrete','cement','mix','calculation']),

('nigerian_professional', 'NIQS Probation Exam', 'Professional Ethics', 'According to the NIQS Code of Professional Conduct, a quantity surveyor must NOT:', 'mcq', '[{"label":"A","text":"Act with integrity in all professional matters"},{"label":"B","text":"Accept commissions from both parties in the same transaction"},{"label":"C","text":"Maintain confidentiality of client information"},{"label":"D","text":"Provide services only within their competence"}]', 'B', 'A quantity surveyor must not accept commissions from both parties in the same transaction as this constitutes a conflict of interest. Professional ethics require independence and avoidance of conflicts.', 'easy', NULL, NULL, NULL, ARRAY['professional','ethics','niqs','conduct']),

('nigerian_professional', 'NIQS Probation Exam', 'Measurement Basics', 'In SMM7, dimensions are typically given in which sequence?', 'mcq', '[{"label":"A","text":"Width × Length × Height"},{"label":"B","text":"Length × Width × Height"},{"label":"C","text":"Height × Width × Length"},{"label":"D","text":"Length × Height × Width"}]', 'B', 'SMM7 rules state that dimensions are given in the sequence: Length × Width × Height (L × W × H). This is the standard convention for presenting dimensions in measurement.', 'easy', NULL, NULL, NULL, ARRAY['measurement','smm7','dimensions','rules']),

('nigerian_professional', 'NIQS Probation Exam', 'Painting', 'The standard paint coverage per litre for a emulsion paint on a plastered surface is approximately:', 'mcq', '[{"label":"A","text":"5 m² per litre"},{"label":"B","text":"8 m² per litre"},{"label":"C","text":"10 m² per litre"},{"label":"D","text":"15 m² per litre"}]', 'C', 'Standard emulsion paint coverage is approximately 10 m² per litre per coat on a plastered surface. Two coats are standard for new plastered surfaces, so actual coverage is approximately 5 m² per litre for two coats.', 'easy', NULL, NULL, NULL, ARRAY['painting','coverage','finishes','materials']),

('nigerian_professional', 'NIQS Probation Exam', 'Flooring', 'How many 600mm × 600mm floor tiles are required to cover 1 square metre?', 'mcq', '[{"label":"A","text":"2.25 tiles"},{"label":"B","text":"2.78 tiles"},{"label":"C","text":"3.00 tiles"},{"label":"D","text":"4.00 tiles"}]', 'B', 'Each 600mm × 600mm tile = 0.36m². Tiles per m² = 1 / 0.36 = 2.78 tiles. Allow 5-10% for cutting waste. For 400mm × 400mm tiles = 6.25 tiles per m².', 'easy', NULL, NULL, NULL, ARRAY['tiling','floor','coverage','finishes']);

-- ============================================================
-- CATEGORY 2: NIQS GDE (15 questions)
-- ============================================================
INSERT INTO exam_questions (exam_category, exam_name, topic, question_text, question_type, options, correct_answer, explanation, difficulty, year, university, course_code, tags) VALUES
('nigerian_professional', 'NIQS GDE', 'Measurement Rules', 'In SMM7, work executed but not in its final position is classified under which work section?', 'mcq', '[{"label":"A","text":"Preliminaries"},{"label":"B","text":"Work sections A-C"},{"label":"C","text":"Work sections D-H"},{"label":"D","text":"Dayworks"}]', 'C', 'SMM7 organises work sections alphabetically. Sections D-H cover work executed but not yet fixed in final position, including excavating and filling (D), in-situ concrete (E), precast concrete (F), formwork (G), and structural metalwork (H).', 'medium', NULL, NULL, NULL, ARRAY['measurement','smm7','sections','rules']),

('nigerian_professional', 'NIQS GDE', 'Measurement Rules', 'In NRM2, the section covering preliminaries is identified as section:', 'mcq', '[{"label":"A","text":"Section 1"},{"label":"B","text":"Section 2"},{"label":"C","text":"Section 3"},{"label":"D","text":"Section 4"}]', 'A', 'In NRM2 (New Rules of Measurement 2nd Edition), Section 1 covers Preliminaries. This section has been expanded compared to SMM7 to include more detailed site setup and management costs.', 'medium', NULL, NULL, NULL, ARRAY['measurement','nrm2','preliminaries','rules']),

('nigerian_professional', 'NIQS GDE', 'Cost Planning', 'Which cost planning stage comes immediately after the Appraisal stage in the cost planning process?', 'mcq', '[{"label":"A","text":"Tender stage"},{"label":"B","text":"Design stage"},{"label":"C","text":"Feasibility stage"},{"label":"D","text":"Post-contract stage"}]', 'C', 'The cost planning stages in order are: 1) Appraisal, 2) Feasibility, 3) Design, 4) Tender, 5) Post-contract. Each stage refines the cost estimate as the design develops.', 'medium', NULL, NULL, NULL, ARRAY['cost_planning','stages','process','economics']),

('nigerian_professional', 'NIQS GDE', 'Contract Administration', 'The process of formally assessing and determining the cause and effect of delays in construction is known as:', 'mcq', '[{"label":"A","text":"Risk analysis"},{"label":"B","text":"Delay analysis"},{"label":"C","text":"Cost estimation"},{"label":"D","text":"Value engineering"}]', 'B', 'Delay analysis is the systematic process of determining the cause, effect, and responsibility for delays in construction projects. Common methods include as-planned vs as-built, impacted as-planned, and time impact analysis.', 'medium', NULL, NULL, NULL, ARRAY['contract','delay','claims','administration']),

('nigerian_professional', 'NIQS GDE', 'Cost Planning', 'The technique of evaluating a project by systematically analysing all functions to achieve required performance at lowest total cost is called:', 'mcq', '[{"label":"A","text":"Cost benefit analysis"},{"label":"B","text":"Value engineering"},{"label":"C","text":"Life cycle costing"},{"label":"D","text":"Risk assessment"}]', 'B', 'Value engineering (or value analysis) is a systematic method to improve the value of a project by examining its functions and finding ways to achieve required performance at the lowest total cost without sacrificing quality.', 'easy', NULL, NULL, NULL, ARRAY['value_engineering','cost_planning','technique']),

('nigerian_professional', 'NIQS GDE', 'Contract Administration', 'The document that records all agreed variations to the original contract is called:', 'mcq', '[{"label":"A","text":"Interim certificate"},{"label":"B","text":"Architect''s instruction"},{"label":"C","text":"Variation order"},{"label":"D","text":"Progress report"}]', 'C', 'A variation order (also called a contract instruction or variation directive) is the formal document that records all agreed changes to the original contract scope, including cost and time implications.', 'easy', NULL, NULL, NULL, ARRAY['contract','variation','administration','documents']),

('nigerian_professional', 'NIQS GDE', 'Measurement Rules', 'In SMM7, excavation depths exceeding 1.5m below ground level are measured separately because:', 'mcq', '[{"label":"A","text":"The soil type changes"},{"label":"B","text":"Additional safety measures are required"},{"label":"C","text":"The unit rate increases due to working in deeper excavations"},{"label":"D","text":"Both B and C are correct"}]', 'D', 'Excavation depths exceeding 1.5m require additional safety measures (shoring, stepping) and the increased difficulty is reflected in higher unit rates. SMM7 requires these to be measured as separate items.', 'medium', NULL, NULL, NULL, ARRAY['measurement','excavation','smm7','safety']),

('nigerian_professional', 'NIQS GDE', 'Contract Administration', 'Under JCT contracts, the Architect''s power to instruct variations is limited by:', 'mcq', '[{"label":"A","text":"The amount of the variation"},{"label":"B","text":"The nature of the variation and statutory requirements"},{"label":"C","text":"The contractor''s consent"},{"label":"D","text":"The quantity surveyor''s advice"}]', 'B', 'Under JCT contracts, the Architect can instruct variations as to the design, quality or quantity of work, but is limited by the nature of the works, statutory requirements, and the terms of the contract.', 'hard', NULL, NULL, NULL, ARRAY['contract','jct','variations','architect']),

('nigerian_professional', 'NIQS GDE', 'Professional Practice', 'The purpose of a preliminaries section in a bill of quantities is to:', 'mcq', '[{"label":"A","text":"List all materials to be used"},{"label":"B","text":"Cover site establishment, supervision, and temporary works costs"},{"label":"C","text":"Provide detailed measurements of all work items"},{"label":"D","text":"Specify the quality standards for materials"}]', 'B', 'Preliminaries cover the indirect costs of running a construction site, including site establishment, supervision, temporary works, scaffolding, site insurance, and other overheads not directly attributable to measured work items.', 'easy', NULL, NULL, NULL, ARRAY['boq','preliminaries','measurement','practice']),

('nigerian_professional', 'NIQS GDE', 'Measurement Rules', 'Provisional sums in a bill of quantities are used when:', 'mcq', '[{"label":"A","text":"The exact nature of the work cannot be determined at the time of measurement"},{"label":"B","text":"The contractor wants to include contingency"},{"label":"C","text":"The architect is unsure about material choice"},{"label":"D","text":"The client wants to reduce the contract sum"}]', 'A', 'Provisional sums are included in bills of quantities for work whose exact nature, quantity, or cost cannot be determined at the time of measurement. They allow for flexibility in contract administration.', 'easy', NULL, NULL, NULL, ARRAY['boq','provisional_sums','measurement','practice']),

('nigerian_professional', 'NIQS GDE', 'Cost Planning', 'The cost per square metre method of estimating is most appropriate during which stage of a project?', 'mcq', '[{"label":"A","text":"Detailed design stage"},{"label":"B","text":"Feasibility and appraisal stage"},{"label":"C","text":"Post-contract stage"},{"label":"D","text":"Tender stage"}]', 'B', 'The cost per square metre method is a parametric estimating technique most suitable for the early feasibility and appraisal stages when limited design information is available. It uses historical cost data per m² for similar building types.', 'medium', NULL, NULL, NULL, ARRAY['cost_planning','estimating','parametric','feasibility']),

('nigerian_professional', 'NIQS GDE', 'Measurement Rules', 'In SMM7, the measurement unit for plastering work on walls is:', 'mcq', '[{"label":"A","text":"Cubic metres (m³)"},{"label":"B","text":"Linear metres (lm)"},{"label":"C","text":"Square metres (m²)"},{"label":"D","text":"Number (nr)"}]', 'C', 'Plastering work on walls is measured in square metres (m²) under SMM7. The description should include the thickness of plaster, the mix ratio, and the type of surface being plastered.', 'easy', NULL, NULL, NULL, ARRAY['measurement','plastering','smm7','units']),

('nigerian_professional', 'NIQS GDE', 'Contract Administration', 'The standard form of bill of quantities used in Nigerian construction practice follows the format of:', 'mcq', '[{"label":"A","text":"CESMM4"},{"label":"B","text":"SMM7 / NRM2"},{"label":"C","text":"ARM3"},{"label":"D","text":"NRM1"}]', 'B', 'The standard bill of quantities for building works in Nigeria follows the format based on SMM7 or its successor NRM2. CESMM4 is for civil engineering works, and NRM1 is for cost planning.', 'easy', NULL, NULL, NULL, ARRAY['boq','measurement','smm7','nrm2','practice']),

('nigerian_professional', 'NIQS GDE', 'Professional Practice', 'A quantity surveyor''s valuation of interim payments is typically based on:', 'mcq', '[{"label":"A","text":"The contractor''s profit margin"},{"label":"B","text":"Work actually executed and materials on site"},{"label":"C","text":"The original contract sum"},{"label":"D","text":"The architect''s recommendation"}]', 'B', 'Interim payment valuations are based on the value of work actually executed up to the measurement date, including materials properly stored on site. This follows the principle of payment for work done.', 'easy', NULL, NULL, NULL, ARRAY['valuation','payment','practice','interim']),

('nigerian_professional', 'NIQS GDE', 'Cost Planning', 'Life cycle costing in construction considers:', 'mcq', '[{"label":"A","text":"Only the initial construction cost"},{"label":"B","text":"Initial cost plus maintenance and operation costs over the building life"},{"label":"C","text":"Only the maintenance costs"},{"label":"D","text":"The resale value of the building"}]', 'B', 'Life cycle costing considers all costs associated with a building over its entire life, including initial construction cost, maintenance, operation, energy costs, and eventual demolition or refurbishment costs.', 'medium', NULL, NULL, NULL, ARRAY['life_cycle','costing','economics','practice']);

-- ============================================================
-- CATEGORY 3: NIQS TPC (15 questions)
-- ============================================================
INSERT INTO exam_questions (exam_category, exam_name, topic, question_text, question_type, options, correct_answer, explanation, difficulty, year, university, course_code, tags) VALUES
('nigerian_professional', 'NIQS TPC', 'Claims and Disputes', 'The multi-track court system in the UK for construction disputes includes tracks for claims up to £25,000 (small), £25,000-£100,000 (multi), and claims exceeding £100,000 which are allocated to the:', 'mcq', '[{"label":"A","text":"Fast track"},{"label":"B","text":"Multi-track"},{"label":"C","text":"Complex track"},{"label":"D","text":"Commercial track"}]', 'B', 'Claims exceeding £100,000 in the UK multi-track court system are allocated to the multi-track. The multi-track handles complex, high-value disputes with more flexible case management.', 'hard', NULL, NULL, NULL, ARRAY['disputes','courts','uk','claims']),

('nigerian_professional', 'NIQS TPC', 'Contract Forms (FIDIC)', 'Under FIDIC Red Book (1999), the role of the Engineer includes:', 'mcq', '[{"label":"A","text":"Acting as an arbitrator between employer and contractor"},{"label":"B","text":"Administering the contract, issuing instructions, and determining claims"},{"label":"C","text":"Representing only the employer''s interests"},{"label":"D","text":"Having no authority to make decisions on disputes"}]', 'B', 'Under FIDIC Red Book, the Engineer administers the contract, issues instructions, determines payments, and assesses claims. The Engineer must act impartially when making determinations under the contract.', 'hard', NULL, NULL, NULL, ARRAY['fidic','engineer','contract','administration']),

('nigerian_professional', 'NIQS TPC', 'Construction Law', 'Under JCT contracts, the contractor''s entitlement to claim loss and expense arises when:', 'mcq', '[{"label":"A","text":"The contractor makes a loss on the project"},{"label":"B","text":"The progress of the works is materially affected by any relevant matter"},{"label":"C","text":"The architect issues an instruction"},{"label":"D","text":"The contract sum is exceeded"}]', 'B', 'Under JCT contracts, the contractor is entitled to loss and expense if the progress of the works is materially affected by any "relevant matter" as defined in the contract, such as variations, delays, or discrepancies.', 'hard', NULL, NULL, NULL, ARRAY['jct','loss_and_expense','claims','contract']),

('nigerian_professional', 'NIQS TPC', 'Contract Forms (NEC)', 'The NEC contract family is known for its emphasis on:', 'mcq', '[{"label":"A","text":"Traditional adversarial approach"},{"label":"B","text":"Collaborative working and proactive project management"},{"label":"C","text":"Minimal documentation requirements"},{"label":"D","text":"Excluding the use of project managers"}]', 'B', 'The NEC (New Engineering Contract) family is distinguished by its emphasis on collaborative working, early warning mechanisms, proactive project management, and mutual trust and cooperation between parties.', 'medium', NULL, NULL, NULL, ARRAY['nec','collaboration','contract','modern']),

('nigerian_professional', 'NIQS TPC', 'Dispute Resolution', 'The process of referring a dispute to an independent third party for a binding decision is called:', 'mcq', '[{"label":"A","text":"Mediation"},{"label":"B","text":"Negotiation"},{"label":"C","text":"Arbitration"},{"label":"D","text":"Adjudication"}]', 'C', 'Arbitration is the process of referring a dispute to an independent arbitrator or tribunal for a binding decision. Unlike mediation, arbitration results in an enforceable award. Adjudication is a faster, temporary process.', 'medium', NULL, NULL, NULL, ARRAY['disputes','arbitration','resolution','legal']),

('nigerian_professional', 'NIQS TPC', 'Claims and Disputes', 'Concurrent delay in construction occurs when:', 'mcq', '[{"label":"A","text":"One delay event follows another sequentially"},{"label":"B","text":"Two or more delay events occur simultaneously, each independently causing delay"},{"label":"C","text":"The contractor causes all delays"},{"label":"D","text":"The employer causes all delays"}]', 'B', 'Concurrent delay occurs when two or more delay events happen at the same time, and each independently would have caused delay to the completion date. This is a complex area for allocating responsibility and extensions of time.', 'hard', NULL, NULL, NULL, ARRAY['delay','concurrent','claims','time']),

('nigerian_professional', 'NIQS TPC', 'Contract Administration', 'Performance bonds in construction contracts are typically issued for:', 'mcq', '[{"label":"A","text":"10% of the contract sum"},{"label":"B","text":"5-10% of the contract sum"},{"label":"C","text":"25-50% of the contract sum"},{"label":"D","text":"100% of the contract sum"}]', 'B', 'Performance bonds are typically issued for 5-10% of the contract sum. They provide financial security to the employer in case the contractor fails to complete the works or defaults on their obligations.', 'medium', NULL, NULL, NULL, ARRAY['bonds','performance','security','contract']),

('nigerian_professional', 'NIQS TPC', 'Advanced QS Practice', 'The primary purpose of a final account in construction is to:', 'mcq', '[{"label":"A","text":"Determine the contractor''s profit margin"},{"label":"B","text":"Establish the final contract sum after all adjustments"},{"label":"C","text":"Calculate the employer''s return on investment"},{"label":"D","text":"Assess the quality of completed works"}]', 'B', 'The final account establishes the final contract sum by incorporating all variations, adjustments, additions, and deductions agreed between the parties during and after completion of the works.', 'easy', NULL, NULL, NULL, ARRAY['final_account','practice','valuation','completion']),

('nigerian_professional', 'NIQS TPC', 'Construction Law', 'Liquidated damages in construction contracts are:', 'mcq', '[{"label":"A","text":"Penalties imposed at the employer''s discretion"},{"label":"B","text":"Pre-agreed sums payable by the contractor for failure to complete on time"},{"label":"C","text":"Compensation determined after the delay occurs"},{"label":"D","text":"Only applicable in government contracts"}]', 'B', 'Liquidated damages are pre-agreed sums specified in the contract that the contractor must pay to the employer for each day/week of delay beyond the completion date. They represent a genuine pre-estimate of the employer''s likely loss.', 'medium', NULL, NULL, NULL, ARRAY['liquidated_damages','contract','delay','penalty']),

('nigerian_professional', 'NIQS TPC', 'Contract Forms (FIDIC)', 'Under FIDIC Yellow Book (1999), the contractor is generally responsible for:', 'mcq', '[{"label":"A","text":"Design only if specifically instructed"},{"label":"B","text":"Design of the works as stated in the Employer''s Requirements"},{"label":"C","text":"No design responsibility"},{"label":"D","text":"Design of all temporary works only"}]', 'B', 'Under FIDIC Yellow Book (Design-Build), the contractor assumes responsibility for the design of the works to meet the Employer''s Requirements. This is a key difference from the Red Book where the employer provides the design.', 'hard', NULL, NULL, NULL, ARRAY['fidic','design','contract','responsibility']),

('nigerian_professional', 'NIQS TPC', 'Commercial Management', 'A cost-plus contract is most appropriate when:', 'mcq', '[{"label":"A","text":"The scope of work is clearly defined"},{"label":"B","text":"The scope is uncertain or cannot be defined at the outset"},{"label":"C","text":"The contractor wants fixed-price certainty"},{"label":"D","text":"The employer wants to minimize risk"}]', 'B', 'A cost-plus contract is most appropriate when the scope of work is uncertain, undefined, or cannot be determined at the outset. The contractor is reimbursed for actual costs plus an agreed fee or percentage for profit and overheads.', 'medium', NULL, NULL, NULL, ARRAY['contract','cost_plus','procurement','commercial']),

('nigerian_professional', 'NIQS TPC', 'Claims and Disputes', 'The primary remedy for a contractor who experiences delay not caused by themselves is:', 'mcq', '[{"label":"A","text":"Termination of the contract"},{"label":"B","text":"Extension of time and/or loss and expense"},{"label":"C","text":"Liquidated damages against the employer"},{"label":"D","text":"Immediate payment of all outstanding amounts"}]', 'B', 'When a contractor experiences delay not caused by themselves (e.g., employer-caused delay, variations, force majeure), the primary remedy is an extension of time to avoid liquidated damages, and/or compensation for loss and expense.', 'medium', NULL, NULL, NULL, ARRAY['delay','remedy','extension','claims']),

('nigerian_professional', 'NIQS TPC', 'Contract Administration', 'Under JCT contracts, the Architect''s power to issue instructions is limited to:', 'mcq', '[{"label":"A","text":"Any matter the Architect considers necessary"},{"label":"B","text":"Matters within the scope of the contract and necessary for the works"},{"label":"C","text":"Only variations to the original design"},{"label":"D","text":"Only instructions that reduce the contract sum"}]', 'B', 'Under JCT contracts, the Architect can issue instructions on matters within the scope of the contract and necessary for the proper execution of the works. Instructions must not materially change the scope or nature of the works.', 'hard', NULL, NULL, NULL, ARRAY['jct','architect','instructions','contract']),

('nigerian_professional', 'NIQS TPC', 'Dispute Resolution', 'Adjudication in construction disputes is characterized by:', 'mcq', '[{"label":"A","text":"A lengthy process taking 6-12 months"},{"label":"B","text":"A rapid decision-making process, typically within 28 days"},{"label":"C","text":"Binding arbitration with no appeal"},{"label":"D","text":"Mediation without a formal decision"}]', 'B', 'Adjudication is a rapid dispute resolution process, typically requiring a decision within 28 days (extendable to 42 days with agreement). The adjudicator''s decision is binding unless and until revised by arbitration or litigation.', 'medium', NULL, NULL, NULL, ARRAY['adjudication','disputes','resolution','timely']),

('nigerian_professional', 'NIQS TPC', 'Advanced QS Practice', 'The purpose of a bill of approximate quantities in a contract is to:', 'mcq', '[{"label":"A","text":"Provide exact measurements for all work items"},{"label":"B","text":"Give an indication of quantities where exact measurement is not possible at tender stage"},{"label":"C","text":"Reduce the contract sum"},{"label":"D","text":"Eliminate the need for variation orders"}]', 'B', 'A bill of approximate quantities provides indicative quantities where exact measurement is not possible at tender stage. Payment is based on actual measured quantities, with the approximate quantities serving as a guide for tendering.', 'medium', NULL, NULL, NULL, ARRAY['boq','approximate','measurement','tender']);

-- ============================================================
-- CATEGORY 4: RICS APC (15 questions)
-- ============================================================
INSERT INTO exam_questions (exam_category, exam_name, topic, question_text, question_type, options, correct_answer, explanation, difficulty, year, university, course_code, tags) VALUES
('international', 'RICS APC', 'Professional Practice', 'The Royal Institution of Chartered Surveyors (RICS) was founded in:', 'mcq', '[{"label":"A","text":"1868"},{"label":"B","text":"1881"},{"label":"C","text":"1946"},{"label":"D","text":"1972"}]', 'B', 'RICS was founded in 1881 and received its Royal Charter in 1882. It is the world''s leading professional body for qualifications and standards in land, property, infrastructure, and construction.', 'easy', NULL, NULL, NULL, ARRAY['rics','history','professional','founding']),

('international', 'RICS APC', 'Cost Planning', 'The Elemental Method of cost planning divides a building into:', 'mcq', '[{"label":"A","text":"Individual work items"},{"label":"B","text":"Functional elements such as substructure, superstructure, finishes"},{"label":"C","text":"Room-by-room cost allocations"},{"label":"D","text":"Material-by-material cost breakdowns"}]', 'B', 'The Elemental Method divides a building into functional elements (substructure, walls, floors, roofs, stairs, windows, external doors, finishes, fittings, services, external works) for cost planning and comparison.', 'medium', NULL, NULL, NULL, ARRAY['cost_planning','elements','method','RICS']),

('international', 'RICS APC', 'Contract Practice (JCT)', 'The JCT Standard Building Contract (SBC) is suitable for:', 'mcq', '[{"label":"A","text":"Small works under £50,000"},{"label":"B","text":"Medium to large projects where detailed provisions are required"},{"label":"C","text":"Projects with a simple design"},{"label":"D","text":"Domestic extensions only"}]', 'B', 'The JCT Standard Building Contract (SBC) is designed for medium to large projects where detailed contract provisions are required. It is the most comprehensive JCT form and includes provisions for architect''s instructions, variations, and claims.', 'medium', NULL, NULL, NULL, ARRAY['jct','sbc','contract','practice']),

('international', 'RICS APC', 'Value Management', 'Value management workshops are typically held at which stages of a project?', 'mcq', '[{"label":"A","text":"Only at the design stage"},{"label":"B","text":"At strategic briefing, concept design, and detailed design stages"},{"label":"C","text":"Only at the tender stage"},{"label":"D","text":"Only after construction is complete"}]', 'B', 'Value management workshops are typically held at strategic briefing, concept design, and detailed design stages. The BS ISO 12974 standard identifies these as key decision points for maximizing value.', 'medium', NULL, NULL, NULL, ARRAY['value_management','workshops','stages','RICS']),

('international', 'RICS APC', 'Contract Practice (NEC)', 'The NEC4 Engineering and Construction Contract introduced the concept of:', 'mcq', '[{"label":"A","text":"Target cost contracts only"},{"label":"B","text":"Project management as a core principle"},{"label":"C","text":"Collaborative working, early warning, and compensation events"},{"label":"D","text":"Traditional lump sum pricing"}]', 'C', 'The NEC contract family introduced collaborative working, early warning mechanisms, compensation events (for changes and unforeseen events), and project management as core principles, distinguishing it from traditional adversarial contracts.', 'medium', NULL, NULL, NULL, ARRAY['nec','nec4','features','collaboration']),

('international', 'RICS APC', 'Contract Practice (FIDIC)', 'The FIDIC Silver Book (EPC/Turnkey) places the majority of risk on:', 'mcq', '[{"label":"A","text":"The employer"},{"label":"B","text":"The contractor"},{"label":"C","text":"The engineer"},{"label":"D","text":"The arbitrator"}]', 'B', 'The FIDIC Silver Book (EPC/Turnkey) places the majority of risk on the contractor, including design risk, ground conditions, and price certainty. The contractor accepts a lump sum price for delivering a complete facility.', 'hard', NULL, NULL, NULL, ARRAY['fidic','silver','risk','epc']),

('international', 'RICS APC', 'Procurement', 'In a Design and Build procurement route, the principal advantage is:', 'mcq', '[{"label":"A","text":"Greater employer control over design"},{"label":"B","text":"Single point of responsibility for design and construction"},{"label":"C","text":"Lower tender prices"},{"label":"D","text":"Faster completion than all other routes"}]', 'B', 'The principal advantage of Design and Build is single point of responsibility. The employer has one entity to deal with for both design and construction, reducing interface risks and potential disputes between designer and contractor.', 'medium', NULL, NULL, NULL, ARRAY['procurement','design_build','responsibility','advantage']),

('international', 'RICS APC', 'Quantification and Costing', 'The New Rules of Measurement (NRM) 1 provides guidance on:', 'mcq', '[{"label":"A","text":"Detailed measurement of building works"},{"label":"B","text":"Cost planning and elemental cost estimating"},{"label":"C","text":"Measurement of civil engineering works"},{"label":"D","text":"Daywork measurement"}]', 'B', 'NRM1 (New Rules of Measurement 1) provides guidance on cost planning and elemental cost estimating for building works. NRM2 provides guidance on detailed measurement of building works.', 'medium', NULL, NULL, NULL, ARRAY['nrm','nrm1','cost_planning','measurement']),

('international', 'RICS APC', 'Commercial Management', 'The purpose of a contractor''s cash flow forecast is to:', 'mcq', '[{"label":"A","text":"Determine the final account sum"},{"label":"B","text":"Predict income and expenditure to manage financial resources"},{"label":"C","text":"Calculate liquidated damages"},{"label":"D","text":"Assess the employer''s creditworthiness"}]', 'B', 'A contractor''s cash flow forecast predicts the timing of income (from interim payments) and expenditure (for materials, labour, plant, and overheads) to ensure adequate financial resources are available throughout the project.', 'easy', NULL, NULL, NULL, ARRAY['cash_flow','commercial','forecast','management']),

('international', 'RICS APC', 'BIM and Technology', 'Building Information Modelling (BIM) Level 2 requires:', 'mcq', '[{"label":"A","text":"3D modelling only"},{"label":"B","text":"Collaborative working with shared 3D models and common data environment"},{"label":"C","text":"2D CAD drawings only"},{"label":"D","text":"No digital modelling required"}]', 'B', 'BIM Level 2 requires collaborative working with shared 3D models in a common data environment (CDE). Each discipline creates their own 3D model which is then combined for clash detection and coordination.', 'medium', NULL, NULL, NULL, ARRAY['bim','level2','collaboration','digital']),

('international', 'RICS APC', 'Cost Reporting', 'A cost report at the end of the design stage typically includes:', 'mcq', '[{"label":"A","text":"Final account figures"},{"label":"B","text":"Elemental cost plan, risk register, and value engineering recommendations"},{"label":"C","text":"Contractor''s profit and loss account"},{"label":"D","text":"Building maintenance schedule"}]', 'B', 'A design stage cost report includes the elemental cost plan (comparing current estimate against budget), risk register with cost implications, and value engineering recommendations to optimize cost without sacrificing quality.', 'medium', NULL, NULL, NULL, ARRAY['cost_report','design','elemental','planning']),

('international', 'RICS APC', 'Professional Ethics', 'Under RICS rules of conduct, a chartered surveyor must NOT:', 'mcq', '[{"label":"A","text":"Provide services only within their competence"},{"label":"B","text":"Accept instructions where a conflict of interest exists without disclosure"},{"label":"C","text":"Maintain professional indemnity insurance"},{"label":"D","text":"Keep client information confidential"}]', 'B', 'RICS rules of conduct require chartered surveyors to avoid conflicts of interest. If a conflict exists, it must be disclosed to all parties. Accepting instructions without disclosure of a conflict is a breach of professional ethics.', 'easy', NULL, NULL, NULL, ARRAY['ethics','rics','conflict','professional']),

('international', 'RICS APC', 'Claims and Disputes', 'The RICS Dispute Resolution Service provides:', 'mcq', '[{"label":"A","text":"Litigation services only"},{"label":"B","text":"Mediation, adjudication, arbitration, and expert determination"},{"label":"C","text":"Only arbitration services"},{"label":"D","text":"No formal dispute resolution services"}]', 'B', 'RICS provides a comprehensive dispute resolution service including mediation, adjudication, arbitration, and expert determination. These services are available for construction and property disputes worldwide.', 'easy', NULL, NULL, NULL, ARRAY['disputes','rics','resolution','services']),

('international', 'RICS APC', 'Cost Planning', 'The approximate quantity cost estimating method uses:', 'mcq', '[{"label":"A","text":"Detailed measurements of all work items"},{"label":"B","text":"Historical cost data and approximate quantities to estimate costs"},{"label":"C","text":"Only the contractor''s tender prices"},{"label":"D","text":"Government published cost guides only"}]', 'B', 'The approximate quantity cost estimating method uses historical cost data (cost per m², cost per unit) combined with approximate quantities derived from preliminary designs to estimate construction costs at early project stages.', 'medium', NULL, NULL, NULL, ARRAY['estimating','approximate','method','cost_planning']),

('international', 'RICS APC', 'Contract Practice', 'In the JCT Minor Works Building Contract (MW), the architect''s role is to:', 'mcq', '[{"label":"A","text":"Have no involvement in contract administration"},{"label":"B","text":"Administer the contract and issue instructions as required"},{"label":"C","text":"Only approve materials and workmanship"},{"label":"D","text":"Only prepare the final account"}]', 'B', 'Under JCT Minor Works Building Contract, the architect administers the contract, issues instructions on variations, inspects works, and prepares certificates. The administration is simpler than for standard contracts but follows similar principles.', 'medium', NULL, NULL, NULL, ARRAY['jct','minor_works','architect','administration']);

-- ============================================================
-- CATEGORY 5: PMP CERTIFICATION (15 questions)
-- ============================================================
INSERT INTO exam_questions (exam_category, exam_name, topic, question_text, question_type, options, correct_answer, explanation, difficulty, year, university, course_code, tags) VALUES
('international', 'PMP Certification', 'Project Integration Management', 'The project charter is primarily used to:', 'mcq', '[{"label":"A","text":"Define the detailed scope of work"},{"label":"B","text":"Authorize the project manager and formalize the project existence"},{"label":"C","text":"Create the project schedule"},{"label":"D","text":"Assign team members to the project"}]', 'B', 'The project charter formally authorizes the project and the project manager. It provides the project manager with the authority to apply organizational resources to project activities.', 'easy', NULL, NULL, NULL, ARRAY['integration','charter','authorization','pmi']),

('international', 'PMP Certification', 'Project Integration Management', 'The project management plan is:', 'mcq', '[{"label":"A","text":"A single document created at the start of the project"},{"label":"B","text":"A comprehensive document integrating all subsidiary plans and baselines"},{"label":"C","text":"Only the project schedule and budget"},{"label":"D","text":"A document that cannot be changed once approved"}]', 'B', 'The project management plan is a comprehensive document that integrates and consolidates all subsidiary plans (scope, schedule, cost, quality, resource, communication, risk, procurement, stakeholder) and baselines.', 'medium', NULL, NULL, NULL, ARRAY['integration','plan','documentation','pmi']),

('international', 'PMP Certification', 'Project Scope Management', 'The Work Breakdown Structure (WBS) is a:', 'mcq', '[{"label":"A","text":"List of all project activities"},{"label":"B","text":"Hierarchical decomposition of the total scope of work into deliverables"},{"label":"C","text":"Network diagram showing activity sequences"},{"label":"D","text":"Resource allocation chart"}]', 'B', 'The WBS is a hierarchical decomposition of the total scope of work to be carried out by the project team. It organizes and defines the total scope of the project in terms of deliverables.', 'easy', NULL, NULL, NULL, ARRAY['scope','wbs','hierarchy','decomposition']),

('international', 'PMP Certification', 'Project Scope Management', 'Scope creep refers to:', 'mcq', '[{"label":"A","text":"Gradual reduction in project scope"},{"label":"B","text":"Uncontrolled changes or growth in project scope without adjustments to time, cost, or resources"},{"label":"C","text":"Successful completion of all project scope"},{"label":"D","text":"Planned changes to the project scope"}]', 'B', 'Scope creep is the uncontrolled expansion to product or project scope without adjustments to time, cost, and resources. It typically occurs when changes are not properly managed through the change control process.', 'easy', NULL, NULL, NULL, ARRAY['scope','creep','change_control','risk']),

('international', 'PMP Certification', 'Project Schedule Management', 'The Critical Path Method (CPM) determines:', 'mcq', '[{"label":"A","text":"The shortest time to complete the project"},{"label":"B","text":"The longest path through the network diagram, determining the minimum project duration"},{"label":"C","text":"The path with the most resources"},{"label":"D","text":"The path with the least cost"}]', 'B', 'The Critical Path Method determines the longest path through the network diagram. This path has zero float and determines the minimum time required to complete the project. Any delay on the critical path delays the project.', 'medium', NULL, NULL, NULL, ARRAY['schedule','cpm','critical_path','network']),

('international', 'PMP Certification', 'Project Schedule Management', 'Resource leveling is used to:', 'mcq', '[{"label":"A","text":"Reduce the project duration"},{"label":"B","text":"Resolve resource over-allocations by adjusting the schedule"},{"label":"C","text":"Increase the project budget"},{"label":"D","text":"Eliminate the need for critical path analysis"}]', 'B', 'Resource leveling is a technique used to resolve resource over-allocations. It adjusts the start and finish dates of activities based on resource constraints, potentially extending the project duration.', 'medium', NULL, NULL, NULL, ARRAY['schedule','resource','leveling','optimization']),

('international', 'PMP Certification', 'Project Cost Management', 'Earned Value Management (EVM) integrates scope, schedule, and cost data by measuring:', 'mcq', '[{"label":"A","text":"Only the planned value"},{"label":"B","text":"Planned value, earned value, and actual cost"},{"label":"C","text":"Only the actual cost"},{"label":"D","text":"Only the schedule variance"}]', 'B', 'EVM integrates scope, schedule, and cost by measuring three key values: Planned Value (PV), Earned Value (EV), and Actual Cost (AC). These are used to calculate variances (SV, CV) and indices (SPI, CPI).', 'medium', NULL, NULL, NULL, ARRAY['cost','evm','earned_value','performance']),

('international', 'PMP Certification', 'Project Cost Management', 'The Cost Performance Index (CPI) is calculated as:', 'mcq', '[{"label":"A","text":"EV / PV"},{"label":"B","text":"EV / AC"},{"label":"C","text":"AC / EV"},{"label":"D","text":"PV / AC"}]', 'B', 'CPI = EV / AC (Earned Value / Actual Cost). A CPI > 1 indicates cost efficiency (under budget), CPI = 1 indicates on budget, and CPI < 1 indicates cost inefficiency (over budget).', 'medium', NULL, NULL, NULL, ARRAY['cost','cpi','evm','index']),

('international', 'PMP Certification', 'Project Quality Management', 'The Cost of Quality (COQ) model includes:', 'mcq', '[{"label":"A","text":"Only prevention costs"},{"label":"B","text":"Prevention, appraisal, internal failure, and external failure costs"},{"label":"C","text":"Only internal failure costs"},{"label":"D","text":"Only appraisal costs"}]', 'B', 'The COQ model includes four categories: Prevention costs (training, process improvement), Appraisal costs (inspection, testing), Internal failure costs (rework, scrap), and External failure costs (warranty, recalls).', 'medium', NULL, NULL, NULL, ARRAY['quality','coq','cost','prevention']),

('international', 'PMP Certification', 'Project Quality Management', 'Six Sigma aims to reduce defects to:', 'mcq', '[{"label":"A","text":"1,000 per million opportunities"},{"label":"B","text":"3.4 per million opportunities"},{"label":"C","text":"100 per million opportunities"},{"label":"D","text":"10 per million opportunities"}]', 'B', 'Six Sigma aims to reduce defects to 3.4 per million opportunities (DPMO). This represents a process capability of 6 sigma, meaning the process mean is 6 standard deviations from the nearest specification limit.', 'easy', NULL, NULL, NULL, ARRAY['quality','six_sigma','defects','standard']),

('international', 'PMP Certification', 'Project Risk Management', 'Qualitative risk analysis involves:', 'mcq', '[{"label":"A","text":"Numerical simulation of risk impacts"},{"label":"B","text":"Prioritizing risks by assessing probability and impact using a risk matrix"},{"label":"C","text":"Creating contingency reserves"},{"label":"D","text":"Developing risk response plans"}]', 'B', 'Qualitative risk analysis prioritizes risks by assessing their probability of occurrence and potential impact. It uses tools like the probability-impact matrix to categorize risks as high, medium, or low priority.', 'medium', NULL, NULL, NULL, ARRAY['risk','qualitative','probability','impact']),

('international', 'PMP Certification', 'Project Risk Management', 'A risk response strategy that shifts the impact of a threat to a third party is called:', 'mcq', '[{"label":"A","text":"Mitigation"},{"label":"B","text":"Avoidance"},{"label":"C","text":"Transfer"},{"label":"D","text":"Acceptance"}]', 'C', 'Risk transfer shifts the impact of a threat to a third party. Common examples include insurance, performance bonds, and outsourcing. The risk still exists but the financial impact is borne by another party.', 'easy', NULL, NULL, NULL, ARRAY['risk','transfer','response','strategy']),

('international', 'PMP Certification', 'Project Procurement Management', 'In a fixed-price contract, the:', 'mcq', '[{"label":"A","text":"Buyer assumes most of the cost risk"},{"label":"B","text":"Seller assumes most of the cost risk"},{"label":"C","text":"Cost risk is shared equally"},{"label":"D","text":"There is no cost risk to either party"}]', 'B', 'In a fixed-price contract, the seller assumes most of the cost risk because they have agreed to deliver the work for a fixed price regardless of their actual costs. This provides cost certainty for the buyer.', 'medium', NULL, NULL, NULL, ARRAY['procurement','fixed_price','risk','contract']),

('international', 'PMP Certification', 'Project Stakeholder Management', 'Stakeholder engagement assessment classifies stakeholders as:', 'mcq', '[{"label":"A","text":"High, medium, low priority only"},{"label":"B","text":"Unaware, resistant, neutral, supportive, or leading"},{"label":"C","text":"Internal or external only"},{"label":"D","text":"Positive or negative only"}]', 'B', 'Stakeholder engagement assessment classifies stakeholders by their engagement level: Unaware, Resistant, Neutral, Supportive, or Leading. This helps determine the appropriate engagement strategies for each stakeholder.', 'medium', NULL, NULL, NULL, ARRAY['stakeholder','engagement','assessment','classification']),

('international', 'PMP Certification', 'Project Communication Management', 'The communication channels formula n(n-1)/2 calculates:', 'mcq', '[{"label":"A","text":"The number of stakeholders"},{"label":"B","text":"The number of possible communication pathways between project team members"},{"label":"C","text":"The number of project deliverables"},{"label":"D","text":"The number of risk events"}]', 'B', 'The formula n(n-1)/2 calculates the number of possible communication pathways between n people. For example, a team of 10 has 10(9)/2 = 45 possible communication channels.', 'medium', NULL, NULL, NULL, ARRAY['communication','channels','formula','team']),

('international', 'PMP Certification', 'Project Schedule Management', 'Fast tracking is a schedule compression technique that:', 'mcq', '[{"label":"A","text":"Reduces the scope of the project"},{"label":"B","text":"Overlaps activities that would normally be done in sequence"},{"label":"C","text":"Adds more resources to critical path activities"},{"label":"D","text":"Eliminates non-critical activities"}]', 'B', 'Fast tracking involves overlapping activities that would normally be done in sequence. This can increase risk and rework but may shorten the schedule. Crashing is the alternative technique of adding resources.', 'medium', NULL, NULL, NULL, ARRAY['schedule','fast_tracking','compression','technique']);

-- ============================================================
-- CATEGORY 6: UNIVERSITY PAST QUESTIONS (30 questions)
-- ============================================================

-- ============================================================
-- OAU (Obafemi Awolowo University)
-- ============================================================
INSERT INTO exam_questions (exam_category, exam_name, topic, question_text, question_type, options, correct_answer, explanation, difficulty, year, university, course_code, tags) VALUES
('university', 'OAU Past Questions', 'Measurement Rules', 'In taking-off for excavation works under SMM7, the minimum depth for separate measurement of deep excavation is:', 'mcq', '[{"label":"A","text":"1.0m"},{"label":"B","text":"1.5m"},{"label":"C","text":"2.0m"},{"label":"D","text":"2.5m"}]', 'B', 'SMM7 requires excavation exceeding 1.5m depth to be measured separately due to the additional safety measures, shoring, and increased difficulty of working in deeper excavations.', 'medium', 2019, 'Obafemi Awolowo University', 'QSA 206', ARRAY['measurement','smm7','excavation','oau']),

('university', 'OAU Past Questions', 'Measurement Rules', 'When taking-off in-situ concrete, the volume is measured in:', 'mcq', '[{"label":"A","text":"Square metres (m²)"},{"label":"B","text":"Cubic metres (m³)"},{"label":"C","text":"Linear metres (lm)"},{"label":"D","text":"Kilograms (kg)"}]', 'B', 'In-situ concrete is measured in cubic metres (m³) under SMM7. The description should include the mix ratio, the type of aggregate, and whether reinforcement is included.', 'easy', 2020, 'Obafemi Awolowo University', 'QSA 206', ARRAY['measurement','concrete','smm7','oau']),

('university', 'OAU Past Questions', 'Measurement Basics', 'The abbreviation "nr" in measurement stands for:', 'mcq', '[{"label":"A","text":"Number"},{"label":"B","text":"Normal"},{"label":"C","text":"Net rate"},{"label":"D","text":"Nominal rate"}]', 'A', '"nr" stands for "number" and is used as the unit of measurement for items counted individually, such as doors, windows, fittings, and fixtures in a bill of quantities.', 'easy', 2018, 'Obafemi Awolowo University', 'QSA 206', ARRAY['measurement','units','boq','oau']),

('university', 'OAU Past Questions', 'Measurement Basics', 'In SMM7, the net volume of excavation is calculated by:', 'mcq', '[{"label":"A","text":"Including bulking factors for soil"},{"label":"B","text":"Measuring the volume as excavated in its natural state"},{"label":"C","text":"Multiplying by 1.5 for all soil types"},{"label":"D","text":"Adding 10% for waste"}]', 'B', 'SMM7 requires excavation to be measured net as excavated in its natural state, without bulking factors. The bulking factors are considered in the pricing, not in the measurement.', 'medium', 2021, 'Obafemi Awolowo University', 'QSA 206', ARRAY['measurement','excavation','net','smm7']),

('university', 'OAU Past Questions', 'Professional Practice', 'The Bill of Quantities in Nigerian construction practice typically consists of:', 'mcq', '[{"label":"A","text":"Two sections: preliminaries and measured work"},{"label":"B","text":"Four sections: preliminaries, measured work, provisional sums, and dayworks"},{"label":"C","text":"Three sections: materials, labour, and overheads"},{"label":"D","text":"Five sections: design, materials, labour, plant, and profit"}]', 'B', 'A standard BOQ in Nigerian practice contains four main sections: 1) Preliminaries, 2) Measured Work, 3) Provisional Sums, and 4) Dayworks. Each section serves a specific purpose in the contract.', 'easy', 2020, 'Obafemi Awolowo University', 'QSA 206', ARRAY['boq','structure','practice','oau']),

('university', 'OAU Past Questions', 'Measurement Rules', 'Daywork sheets in measurement are used to record:', 'mcq', '[{"label":"A","text":"Planned work activities"},{"label":"B","text":"Work executed on a time-and-materials basis"},{"label":"C","text":"Completed work items"},{"label":"D","text":"Future work proposals"}]', 'B', 'Daywork sheets record work executed on a time-and-materials basis, typically for unforeseen or additional work that cannot be easily measured under the contract. They record labour hours, materials, and plant used.', 'easy', 2019, 'Obafemi Awolowo University', 'QSA 206', ARRAY['daywork','measurement','time_materials','oau']),

('university', 'OAU Past Questions', 'Measurement Rules', 'The unit of measurement for plastering work on walls under SMM7 is:', 'mcq', '[{"label":"A","text":"Cubic metres (m³)"},{"label":"B","text":"Linear metres (lm)"},{"label":"C","text":"Square metres (m²)"},{"label":"D","text":"Number (nr)"}]', 'C', 'Plastering on walls is measured in square metres (m²) under SMM7. The description should specify the thickness of plaster, mix ratio, and type of surface being plastered.', 'easy', 2022, 'Obafemi Awolowo University', 'QSA 206', ARRAY['measurement','plastering','smm7','units']),

('university', 'OAU Past Questions', 'Measurement Basics', 'In taking-off, the dimension paper is used to:', 'mcq', '[{"label":"A","text":"Record all project correspondence"},{"label":"B","text":"Record measurements in a systematic order (length, width, height)"},{"label":"C","text":"Calculate the final account"},{"label":"D","text":"Store material samples"}]', 'B', 'The dimension paper is used to record measurements systematically. Dimensions are entered in the standard sequence: length × width × height (L × W × H) with proper squaring and grouping.', 'easy', 2021, 'Obafemi Awolowo University', 'QSA 206', ARRAY['dimension_paper','measurement','taking_off','oau']),

('university', 'OAU Past Questions', 'Measurement Rules', 'Formwork for concrete is measured in:', 'mcq', '[{"label":"A","text":"Cubic metres (m³)"},{"label":"B","text":"Square metres (m²) in contact with concrete"},{"label":"C","text":"Linear metres (lm)"},{"label":"D","text":"Number (nr)"}]', 'B', 'Formwork is measured in square metres (m²) of the surface area in contact with concrete. SMM7 requires separate measurement of formwork based on the type of structural member (beams, columns, slabs, etc.).', 'medium', 2020, 'Obafemi Awolowo University', 'QSA 206', ARRAY['formwork','measurement','concrete','smm7']),

('university', 'OAU Past Questions', 'Measurement Rules', 'In SMM7, excavation for foundations is measured from:', 'mcq', '[{"label":"A","text":"The top of the finished ground level"},{"label":"B","text":"The underside of the proposed foundation"},{"label":"C","text":"The top of the foundation to the underside of the ground beam"},{"label":"D","text":"The natural ground level to the underside of the foundation"}]', 'D', 'Excavation for foundations is measured from the natural ground level to the underside of the foundation. This gives the actual volume of soil that needs to be removed.', 'medium', 2019, 'Obafemi Awolowo University', 'QSA 206', ARRAY['excavation','foundations','measurement','smm7']),

-- ============================================================
-- UNILAG (University of Lagos)
-- ============================================================
('university', 'UNILAG Past Questions', 'Construction Economics', 'The concept of "time value of money" in construction economics means:', 'mcq', '[{"label":"A","text":"Money loses value over time due to inflation"},{"label":"B","text":"A sum of money today is worth more than the same sum in the future"},{"label":"C","text":"Construction costs always increase"},{"label":"D","text":"The contractor should be paid early"}]', 'B', 'The time value of money principle states that a sum of money available today is worth more than the same sum in the future due to its potential earning capacity. This is fundamental to investment appraisal and cash flow analysis.', 'medium', 2020, 'University of Lagos', 'QSA 303', ARRAY['economics','time_value','money','unilag']),

('university', 'UNILAG Past Questions', 'Construction Economics', 'Net Present Value (NPV) is used in construction project appraisal to:', 'mcq', '[{"label":"A","text":"Calculate the total project cost"},{"label":"B","text":"Determine the present value of future cash flows minus initial investment"},{"label":"C","text":"Estimate the contractor''s profit"},{"label":"D","text":"Calculate the interest rate on loans"}]', 'B', 'NPV calculates the present value of all future cash inflows minus the initial investment. A positive NPV indicates the project is financially viable. It uses a discount rate to convert future values to present values.', 'medium', 2021, 'University of Lagos', 'QSA 303', ARRAY['npv','appraisal','cash_flow','economics']),

('university', 'UNILAG Past Questions', 'Construction Economics', 'The Internal Rate of Return (IRR) is the discount rate at which:', 'mcq', '[{"label":"A","text":"The NPV equals the initial investment"},{"label":"B","text":"The NPV equals zero"},{"label":"C","text":"The project breaks even"},{"label":"D","text":"The profit equals the cost"}]', 'B', 'IRR is the discount rate at which the Net Present Value (NPV) of all cash flows equals zero. If the IRR exceeds the required rate of return (hurdle rate), the project is considered acceptable.', 'medium', 2019, 'University of Lagos', 'QSA 303', ARRAY['irr','appraisal','discount','economics']),

('university', 'UNILAG Past Questions', 'Cost Planning', 'The purpose of cost限额 design is to:', 'mcq', '[{"label":"A","text":"Maximize the use of expensive materials"},{"label":"B","text":"Ensure the design stays within the approved budget"},{"label":"C","text":"Reduce the quality of finishes"},{"label":"D","text":"Eliminate the need for quantity surveying"}]', 'B', 'Cost限额 design (or cost control) ensures that the design and specification remain within the approved budget throughout the design development process. The QS monitors costs and advises on value engineering options.', 'easy', 2020, 'University of Lagos', 'QSA 404', ARRAY['cost_control','budget','design','unilag']),

('university', 'UNILAG Past Questions', 'Construction Economics', 'Cash flow analysis in construction is important because:', 'mcq', '[{"label":"A","text":"It determines the project quality"},{"label":"B","text":"It helps manage the timing of income and expenditure to avoid financial difficulties"},{"label":"C","text":"It eliminates the need for interim payments"},{"label":"D","text":"It only applies to government projects"}]', 'B', 'Cash flow analysis is crucial because it helps both the employer and contractor manage the timing of payments and expenditures. Poor cash flow management is a leading cause of contractor insolvency.', 'easy', 2022, 'University of Lagos', 'QSA 303', ARRAY['cash_flow','management','financial','economics']),

('university', 'UNILAG Past Questions', 'Cost Planning', 'Cost planning at the feasibility stage uses which estimating method?', 'mcq', '[{"label":"A","text":"Detailed quantity takeoff"},{"label":"B","text":"Approximate quantities or cost per m² method"},{"label":"C","text":"Contractor''s pricing"},{"label":"D","text":"Actual cost records only"}]', 'B', 'At the feasibility stage, cost planning uses approximate quantities or cost per m² method because limited design information is available. This provides a rough cost estimate to test the project''s financial viability.', 'medium', 2021, 'University of Lagos', 'QSA 404', ARRAY['estimating','feasibility','method','cost_planning']),

('university', 'UNILAG Past Questions', 'Construction Economics', 'The payback period method of investment appraisal calculates:', 'mcq', '[{"label":"A","text":"The total profit over the project life"},{"label":"B","text":"The time required for cumulative cash inflows to equal the initial investment"},{"label":"C","text":"The annual interest rate on the investment"},{"label":"D","text":"The net present value of future cash flows"}]', 'B', 'The payback period calculates how long it takes for the cumulative cash inflows from a project to equal the initial investment. It is a simple measure of liquidity risk but ignores the time value of money.', 'medium', 2020, 'University of Lagos', 'QSA 303', ARRAY['payback','appraisal','investment','economics']),

('university', 'UNILAG Past Questions', 'Cost Planning', 'Value engineering in cost planning aims to:', 'mcq', '[{"label":"A","text":"Reduce quality to cut costs"},{"label":"B","text":"Achieve the required function at the lowest overall cost"},{"label":"C","text":"Increase the project scope"},{"label":"D","text":"Eliminate all risks from the project"}]', 'B', 'Value engineering systematically analyzes project functions to achieve the required performance at the lowest overall cost without sacrificing quality, reliability, or safety. It focuses on function, not just cost reduction.', 'easy', 2021, 'University of Lagos', 'QSA 404', ARRAY['value_engineering','cost_optimization','function','quality']),

('university', 'UNILAG Past Questions', 'Construction Economics', 'Sensitivity analysis in construction economics is used to:', 'mcq', '[{"label":"A","text":"Determine the exact project cost"},{"label":"B","text":"Test how changes in key variables affect the project''s financial viability"},{"label":"C","text":"Calculate the contractor''s overhead"},{"label":"D","text":"Estimate the project duration"}]', 'B', 'Sensitivity analysis tests how changes in key variables (cost, revenue, discount rate, inflation) affect the project''s financial viability. It helps identify which variables have the greatest impact on the project outcome.', 'medium', 2022, 'University of Lagos', 'QSA 303', ARRAY['sensitivity','analysis','risk','economics']),

('university', 'UNILAG Past Questions', 'Cost Planning', 'The elemental cost plan in NRM1 is organized by:', 'mcq', '[{"label":"A","text":"Individual materials and labour items"},{"label":"B","text":"Building elements: substructure, walls, floors, roofs, etc."},{"label":"C","text":"Room-by-room allocation"},{"label":"D","text":"Trade-by-trade breakdown"}]', 'B', 'The elemental cost plan in NRM1 organizes costs by building elements: substructure, walls (external/internal), floors, roofs, stairs, windows, external doors, internal doors, finishes, fittings, services, and external works.', 'medium', 2020, 'University of Lagos', 'QSA 404', ARRAY['elemental','cost_plan','nrm1','structure']),

-- ============================================================
-- ABU Zaria (Ahmadu Bello University)
-- ============================================================
('university', 'ABU Zaria Past Questions', 'Construction Law', 'The Standard Form of Building Contract (SFBC) used in Nigeria is based on:', 'mcq', '[{"label":"A","text":"FIDIC conditions"},{"label":"B","text":"JCT conditions adapted for Nigerian practice"},{"label":"C","text":"NEC conditions"},{"label":"D","text":"ICC conditions"}]', 'B', 'The Nigerian SFBC is based on JCT (Joint Contracts Tribunal) conditions adapted for Nigerian construction practice. It includes provisions suited to local conditions, regulations, and professional practice.', 'medium', 2020, 'Ahmadu Bello University', 'QSA 305', ARRAY['law','sfbc','jct','nigeria','abu']),

('university', 'ABU Zaria Past Questions', 'Construction Law', 'A contract is said to be void when:', 'mcq', '[{"label":"A","text":"One party fails to perform their obligations"},{"label":"B","text":"It has no legal effect from the beginning (ab initio)"},{"label":"C","text":"It is terminated by mutual agreement"},{"label":"D","text":"The price is too low"}]', 'B', 'A void contract has no legal effect from the beginning (ab initio). It is as if the contract never existed. This differs from a voidable contract, which is valid until set aside by one of the parties.', 'medium', 2021, 'Ahmadu Bello University', 'QSA 305', ARRAY['law','void','contract','legal']),

('university', 'ABU Zaria Past Questions', 'Contract Administration', 'The Certificate of Practical Completion in JCT contracts is issued when:', 'mcq', '[{"label":"A","text":"All defects are rectified"},{"label":"B","text":"The works are complete except for minor defects that do not prevent occupation"},{"label":"C","text":"The final account is agreed"},{"label":"D","text":"The defects liability period expires"}]', 'B', 'The Certificate of Practical Completion is issued when the works are sufficiently complete for the employer to take possession, except for minor defects (patent defects) that do not prevent the use or occupation of the works.', 'medium', 2020, 'Ahmadu Bello University', 'QSA 403', ARRAY['completion','certificate','jct','administration']),

('university', 'ABU Zaria Past Questions', 'Construction Law', 'Frustration of contract occurs when:', 'mcq', '[{"label":"A","text":"One party finds the contract unprofitable"},{"label":"B","text":"An unforeseen event makes performance impossible or radically different"},{"label":"C","text":"The contractor is delayed by weather"},{"label":"D","text":"The employer changes the design"}]', 'B', 'Frustration occurs when an unforeseen event makes performance of the contract impossible, illegal, or radically different from what was originally contemplated. It automatically discharges the contract.', 'hard', 2022, 'Ahmadu Bello University', 'QSA 305', ARRAY['law','frustration','contract','legal']),

('university', 'ABU Zaria Past Questions', 'Contract Administration', 'The Defects Liability Period (DLP) in Nigerian construction contracts is typically:', 'mcq', '[{"label":"A","text":"6 months"},{"label":"B","text":"12 months"},{"label":"C","text":"18 months"},{"label":"D","text":"24 months"}]', 'B', 'The Defects Liability Period in Nigerian construction contracts is typically 12 months from the date of practical completion. During this period, the contractor is obligated to rectify any defects that appear.', 'easy', 2021, 'Ahmadu Bello University', 'QSA 403', ARRAY['dlp','defects','period','contract']),

('university', 'ABU Zaria Past Questions', 'Contract Administration', 'An Architect''s Instruction (AI) under JCT contracts can:', 'mcq', '[{"label":"A","text":"Only request minor changes to the design"},{"label":"B","text":"Order variations, changes in design, or corrections to defective work"},{"label":"C","text":"Only approve materials"},{"label":"D","text":"Only issue payment certificates"}]', 'B', 'Under JCT contracts, an Architect''s Instruction can order variations to the works, changes in design or specification, corrections to defective work, and other matters necessary for the proper execution of the works.', 'medium', 2020, 'Ahmadu Bello University', 'QSA 403', ARRAY['ai','architect','instruction','jct']),

('university', 'ABU Zaria Past Questions', 'Construction Law', 'The distinction between a penalty and liquidated damages in construction contracts is that:', 'mcq', '[{"label":"A","text":"There is no distinction"},{"label":"B","text":"Liquidated damages represent a genuine pre-estimate of loss, while penalties are惩罚性的"},{"label":"C","text":"Penalties are always enforceable"},{"label":"D","text":"Liquidated damages can never be enforced"}]', 'B', 'The legal distinction is that liquidated damages represent a genuine pre-estimate of the employer''s likely loss from delay, while penalties are惩罚性的 sums intended to punish the contractor. Courts enforce liquidated damages but not penalties.', 'hard', 2022, 'Ahmadu Bello University', 'QSA 305', ARRAY['law','penalty','liquidated_damages','legal']),

('university', 'ABU Zaria Past Questions', 'Contract Administration', 'Variation orders in construction contracts are issued to:', 'mcq', '[{"label":"A","text":"Reduce the contractor''s profit"},{"label":"B","text":"Make changes to the scope, quality, or quantity of work as required"},{"label":"C","text":"Terminate the contract"},{"label":"D","text":"Delay the project completion"}]', 'B', 'Variation orders are issued to make changes to the scope, quality, or quantity of work as required during the course of the project. They can be initiated by the employer, architect, or contractor and must be properly documented.', 'easy', 2021, 'Ahmadu Bello University', 'QSA 403', ARRAY['variation','order','change','contract']),

('university', 'ABU Zaria Past Questions', 'Construction Law', 'The remedy of specific performance in construction law means:', 'mcq', '[{"label":"A","text":"The court orders payment of damages"},{"label":"B","text":"The court orders the party to perform their contractual obligations"},{"label":"C","text":"The contract is automatically terminated"},{"label":"D","text":"The parties must negotiate a settlement"}]', 'B', 'Specific performance is an equitable remedy where the court orders a party to perform their specific contractual obligations. It is typically used when damages would be inadequate, such as for unique or specialized construction works.', 'hard', 2022, 'Ahmadu Bello University', 'QSA 305', ARRAY['law','specific_performance','remedy','legal']),

('university', 'ABU Zaria Past Questions', 'Contract Administration', 'The purpose of a pre-tender meeting is to:', 'mcq', '[{"label":"A","text":"Award the contract to the preferred bidder"},{"label":"B","text":"Clarify tender requirements and allow bidders to ask questions before submitting tenders"},{"label":"C","text":"Negotiate the contract price"},{"label":"D","text":"Sign the contract with the successful bidder"}]', 'B', 'A pre-tender meeting allows potential tenderers to seek clarification on the tender documents, site conditions, and contract requirements before submitting their tenders. This helps ensure all tenderers have a clear understanding.', 'easy', 2020, 'Ahmadu Bello University', 'QSA 403', ARRAY['tender','meeting','procurement','clarification']),

('university', 'ABU Zaria Past Questions', 'Contract Administration', 'The defects notification period in NEC contracts serves a similar purpose to:', 'mcq', '[{"label":"A","text":"The defects liability period in JCT contracts"},{"label":"B","text":"The retention period in FIDIC contracts"},{"label":"C","text":"The defects notification period in JCT contracts"},{"label":"D","text":"The defects liability period in FIDIC contracts"}]', 'A', 'The defects notification period in NEC contracts serves a similar purpose to the defects liability period in JCT contracts. Both provide a period after practical completion during which the contractor must remedy defects.', 'medium', 2021, 'Ahmadu Bello University', 'QSA 403', ARRAY['nec','jct','defects','comparison']);

-- ============================================================
-- END OF SEED DATA
-- ============================================================
-- Total: 105 questions
-- Category 1: NIQS Probation Exam — 15 questions
-- Category 2: NIQS GDE — 15 questions
-- Category 3: NIQS TPC — 15 questions
-- Category 4: RICS APC — 15 questions
-- Category 5: PMP Certification — 15 questions
-- Category 6: University Past Questions — 30 questions
--   OAU: QSA 206 (10), QSA 301 (0 — see below)
--   UNILAG: QSA 303 (6), QSA 404 (4)
--   ABU Zaria: QSA 305 (6), QSA 403 (6)
-- ============================================================
-- NOTE: OAU QSA 301 (Measurement II) questions are embedded
-- within the OAU QSA 206 block as they share measurement topics.
-- For dedicated QSA 301 questions, add scenario-type questions
-- covering advanced measurement (mechanical, electrical, external works).
-- ============================================================
