const ExcelJS = require('exceljs');

const formatNaira = (n) => Number(n || 0).toFixed(2);

// ─── BOQ Excel Export ─────────────────────────────────────────
exports.generateBoqExcel = async (boq, branding) => {
  const wb = new ExcelJS.Workbook();
  wb.creator = 'QSToolkit';
  wb.created = new Date();

  const ws = wb.addWorksheet('Bill of Quantities', {
    pageSetup: { paperSize: 9, orientation: 'portrait', fitToPage: true }
  });

  const primary = branding?.primary_color?.replace('#', '') || '1a3c5e';
  const secondary = branding?.secondary_color?.replace('#', '') || 'f59e0b';
  const companyName = branding?.brand_name || 'QSToolkit';

  // Column widths
  ws.columns = [
    { key: 'item_no', width: 10 },
    { key: 'description', width: 45 },
    { key: 'unit', width: 10 },
    { key: 'qty', width: 12 },
    { key: 'rate', width: 16 },
    { key: 'amount', width: 18 }
  ];

  // Title rows
  ws.mergeCells('A1:F1');
  ws.getCell('A1').value = companyName.toUpperCase();
  ws.getCell('A1').font = { bold: true, size: 16, color: { argb: `FF${primary}` } };
  ws.getCell('A1').alignment = { horizontal: 'center' };

  ws.mergeCells('A2:F2');
  ws.getCell('A2').value = `BILL OF QUANTITIES — ${boq.projects?.title || boq.title}`;
  ws.getCell('A2').font = { bold: true, size: 12 };
  ws.getCell('A2').alignment = { horizontal: 'center' };

  ws.addRow([]);
  ws.addRow(['Project:', boq.projects?.title || '-', '', 'Client:', boq.client_name || '-', '']);
  ws.addRow(['Location:', boq.location || '-', '', 'Date:', boq.date_prepared || new Date().toISOString().split('T')[0], '']);
  ws.addRow(['Measurement Standard:', boq.measurement_standard || '-', '', '', '', '']);
  ws.addRow([]);

  // Header row
  const headerRow = ws.addRow(['Item No.', 'Description of Work', 'Unit', 'Quantity', 'Rate (₦)', 'Amount (₦)']);
  headerRow.eachCell(cell => {
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: `FF${primary}` } };
    cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    cell.alignment = { horizontal: 'center', vertical: 'middle' };
    cell.border = { bottom: { style: 'medium', color: { argb: 'FFFFFFFF' } } };
  });

  let grandTotal = 0;

  (boq.boq_sections || []).forEach((section, si) => {
    // Section header
    const sectionRow = ws.addRow([
      '', `${String.fromCharCode(65 + si)}. ${section.title} ${section.section_type ? `(${section.section_type})` : ''}`.toUpperCase(), '', '', '', ''
    ]);
    ws.mergeCells(`B${sectionRow.number}:F${sectionRow.number}`);
    sectionRow.eachCell(cell => {
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: `FF${secondary}30` } };
      cell.font = { bold: true, color: { argb: `FF${primary}` } };
    });

    (section.boq_items || []).forEach((item, ii) => {
      const row = ws.addRow([
        item.item_no || `${String.fromCharCode(65 + si)}${ii + 1}`,
        [
          item.description,
          [item.material_type, item.thickness_or_mix, item.finish_type, item.spec_reference].filter(Boolean).join(' | ')
        ].filter(Boolean).join(' | Spec: '),
        item.unit || '-',
        Number(item.quantity || 0),
        Number(item.rate || 0),
        Number(item.amount || 0)
      ]);

      row.getCell(4).numFmt = '#,##0.00';
      row.getCell(5).numFmt = '₦#,##0.00';
      row.getCell(6).numFmt = '₦#,##0.00';
      row.getCell(4).alignment = { horizontal: 'right' };
      row.getCell(5).alignment = { horizontal: 'right' };
      row.getCell(6).alignment = { horizontal: 'right' };

      if (ii % 2 === 0) {
        row.eachCell(cell => {
          cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF9FAFB' } };
        });
      }
    });

    // Section subtotal
    const subtotalRow = ws.addRow([
      '', `Sub-total — ${section.title}`, '', '', '', Number(section.section_total || 0)
    ]);
    subtotalRow.getCell(6).numFmt = '₦#,##0.00';
    subtotalRow.getCell(6).alignment = { horizontal: 'right' };
    subtotalRow.eachCell(cell => { cell.font = { bold: true }; });
    grandTotal += Number(section.section_total || 0);

    ws.addRow([]);
  });

  // Grand total
  const gtRow = ws.addRow(['', 'GRAND TOTAL', '', '', '', grandTotal]);
  gtRow.getCell(6).numFmt = '₦#,##0.00';
  gtRow.eachCell(cell => {
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: `FF${primary}` } };
    cell.font = { bold: true, size: 12, color: { argb: 'FFFFFFFF' } };
    cell.alignment = { horizontal: cell.col === 6 ? 'right' : 'left' };
  });

  ws.addRow([]);
  ws.addRow(['', 'Generated by QSToolkit · qs.solnuv.com']);

  return wb.xlsx.writeBuffer();
};

// ─── Invoice Excel Export ─────────────────────────────────────
exports.generateInvoiceExcel = async (invoice, branding) => {
  const wb = new ExcelJS.Workbook();
  const ws = wb.addWorksheet(invoice.invoice_type === 'quotation' ? 'Quotation' : 'Invoice');
  const primary = branding?.primary_color?.replace('#', '') || '1a3c5e';
  const companyName = branding?.brand_name || 'QSToolkit';

  ws.columns = [
    { key: 'no', width: 6 },
    { key: 'description', width: 40 },
    { key: 'unit', width: 10 },
    { key: 'qty', width: 10 },
    { key: 'price', width: 16 },
    { key: 'amount', width: 18 }
  ];

  ws.mergeCells('A1:F1');
  ws.getCell('A1').value = companyName;
  ws.getCell('A1').font = { bold: true, size: 18, color: { argb: `FF${primary}` } };
  ws.getCell('A1').alignment = { horizontal: 'center' };

  ws.mergeCells('A2:F2');
  ws.getCell('A2').value = invoice.invoice_type?.toUpperCase();
  ws.getCell('A2').font = { bold: true, size: 14 };
  ws.getCell('A2').alignment = { horizontal: 'center' };

  ws.addRow([]);
  ws.addRow(['Invoice No:', invoice.invoice_no, '', 'Client:', invoice.client_name, '']);
  ws.addRow(['Date:', invoice.issue_date, '', 'Email:', invoice.client_email || '-', '']);
  if (invoice.due_date) ws.addRow(['Due Date:', invoice.due_date, '', '', '', '']);
  ws.addRow([]);

  const headerRow = ws.addRow(['#', 'Description', 'Unit', 'Qty', 'Unit Price (₦)', 'Amount (₦)']);
  headerRow.eachCell(cell => {
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: `FF${primary}` } };
    cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
  });

  (invoice.invoice_items || []).forEach((item, i) => {
    const row = ws.addRow([i + 1, item.description, item.unit || '-', Number(item.quantity), Number(item.unit_price), Number(item.amount)]);
    row.getCell(5).numFmt = '₦#,##0.00';
    row.getCell(6).numFmt = '₦#,##0.00';
    if (i % 2 === 0) row.eachCell(c => { c.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF9FAFB' } }; });
  });

  ws.addRow([]);
  ws.addRow(['', '', '', '', 'Subtotal', Number(invoice.subtotal)]).getCell(6).numFmt = '₦#,##0.00';
  if (invoice.vat_percent > 0) ws.addRow(['', '', '', '', `VAT (${invoice.vat_percent}%)`, Number(invoice.vat_amount)]).getCell(6).numFmt = '₦#,##0.00';
  if (invoice.discount_percent > 0) ws.addRow(['', '', '', '', `Discount (${invoice.discount_percent}%)`, -Number(invoice.discount_amount)]).getCell(6).numFmt = '₦#,##0.00';

  const gtRow = ws.addRow(['', '', '', '', 'TOTAL (NGN)', Number(invoice.total_amount)]);
  gtRow.getCell(6).numFmt = '₦#,##0.00';
  gtRow.eachCell(c => { c.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: `FF${primary}` } }; c.font = { bold: true, color: { argb: 'FFFFFFFF' } }; });

  ws.addRow([]);
  ws.addRow(['', 'Generated by QSToolkit · qs.solnuv.com']);

  return wb.xlsx.writeBuffer();
};
