-- ============================================================
--  Migration 041: Add slug to exam_definitions + seed professional exams
--  Fixes: exam start 404/503 by supporting slug-based lookup
-- ============================================================

-- 1. Add slug column to exam_definitions
ALTER TABLE exam_definitions
  ADD COLUMN IF NOT EXISTS slug text;

CREATE UNIQUE INDEX IF NOT EXISTS idx_exam_def_slug ON exam_definitions(slug) WHERE slug IS NOT NULL;

-- 2. Seed professional exam definitions with slugs
-- These match the hardcoded EXAM_DATA slugs in the frontend

-- Nigerian Professional Exams
INSERT INTO exam_definitions (id, exam_name, category, description, time_limit_minutes, total_questions, passing_score, is_published, is_past_question, slug) VALUES
('e0000001-0000-0000-0000-000000000001', 'QSRBN Registration Prep', 'nigerian_professional', 'Prepare for the Quantity Surveyors Registration Board of Nigeria (QSRBN) registration examination. Covers Nigerian construction law, measurement standards, and professional practice.', 90, 50, 60, true, false, 'qsrbn-registration'),
('e0000001-0000-0000-0000-000000000002', 'NIQS Probation Exam', 'nigerian_professional', 'The NIQS probation examination tests foundational knowledge required for Nigerian Quantity Surveyors. Covers measurement, estimation, and professional practice.', 120, 40, 50, true, false, 'niqs-probation'),
('e0000001-0000-0000-0000-000000000003', 'NIQS Intermediate Exam', 'nigerian_professional', 'Intermediate-level examination covering advanced measurement techniques, cost planning, and project management principles for aspiring NIQS members.', 180, 30, 55, true, false, 'niqs-intermediate'),
('e0000001-0000-0000-0000-000000000004', 'NIQS GDE - Graduateship', 'nigerian_professional', 'The NIQS Graduateship Diploma Examination consists of 6 papers covering the full breadth of Quantity Surveying knowledge.', 120, 40, 50, true, false, 'niqs-gde'),
('e0000001-0000-0000-0000-000000000005', 'NIQS TPC - Test of Professional Competence', 'nigerian_professional', 'The Test of Professional Competence is the final examination for NIQS Fellowship. Covers real-world case studies and professional scenarios.', 180, 40, 50, true, false, 'niqs-tpc'),
('e0000001-0000-0000-0000-000000000006', 'NIQS PCI Prep', 'nigerian_professional', 'Practice for the NIQS Professional Competence Interview with mock scenarios, role-plays, and professional judgment questions.', 60, 20, 0, true, false, 'niqs-pci'),
('e0000001-0000-0000-0000-000000000007', 'Job Interview Prep', 'nigerian_professional', 'Prepare for Quantity Surveying job interviews with scenario-based questions, technical MCQs, and situational judgment tests.', 90, 30, 60, true, false, 'job-interview'),

-- International Exams
('e0000001-0000-0000-0000-000000000011', 'RICS APC - QS & Construction', 'international', 'Royal Institution of Chartered Surveyors Assessment of Professional Competence. Covers all competency areas for QS pathway candidates.', 60, 50, 70, true, false, 'rics-apc'),
('e0000001-0000-0000-0000-000000000012', 'CIOB Chartered Membership', 'international', 'Chartered Institute of Building membership examination covering construction management, building technology, and professional practice.', 120, 40, 65, true, false, 'ciob-chartered'),
('e0000001-0000-0000-0000-000000000013', 'PMP Certification', 'international', 'Project Management Professional certification exam covering predictive, agile, and hybrid project management approaches.', 230, 60, 60, true, false, 'pmp-certification'),
('e0000001-0000-0000-0000-000000000014', 'PRINCE2 Foundation', 'international', 'PRINCE2 Foundation certification covering the principles, themes, and processes of the PRINCE2 project management methodology.', 60, 75, 55, true, false, 'prince2-foundation'),
('e0000001-0000-0000-0000-000000000015', 'PRINCE2 Practitioner', 'international', 'PRINCE2 Practitioner certification demonstrating ability to apply and tailor the PRINCE2 methodology to real-world projects.', 150, 60, 55, true, false, 'prince2-practitioner')

ON CONFLICT (id) DO NOTHING;

-- 3. Seed professional exam questions for each professional exam
-- QSRBN Registration Prep questions
INSERT INTO exam_questions (exam_id, exam_category, exam_name, topic, question_text, question_type, options, correct_answer, explanation, difficulty, is_active) VALUES
('e0000001-0000-0000-0000-000000000001', 'nigerian_professional', 'QSRBN Registration Prep', 'Construction Law', 'What is the primary legislation governing construction contracts in Nigeria?', 'mcq', '["JCT Standard Building Contract", "Nigerian Construction Industry Reform Act", "FIDIC Conditions of Contract", "NEC Engineering and Construction Contract"]', 'B', 'The Nigerian Construction Industry Reform Act is the primary legislation governing construction contracts in Nigeria.', 'medium', true),
('e0000001-0000-0000-0000-000000000001', 'nigerian_professional', 'QSRBN Registration Prep', 'Measurement', 'Under SMM7, which rule covers the measurement of concrete works?', 'mcq', '["Rule 1", "Rule 2", "Rule 3", "Rule 4"]', 'C', 'Rule 3 covers concrete works measurement in SMM7.', 'medium', true),
('e0000001-0000-0000-0000-000000000001', 'nigerian_professional', 'QSRBN Registration Prep', 'BOQ Preparation', 'What is the primary function of a bill of quantities?', 'mcq', '["To provide a contract document", "To provide a common basis for tendering", "To set the final contract sum", "To calculate variations"]', 'B', 'The primary function of a BOQ is to provide a common basis for tendering.', 'easy', true),
('e0000001-0000-0000-0000-000000000001', 'nigerian_professional', 'QSRBN Registration Prep', 'Professional Ethics', 'What is the primary duty of a QS to their client?', 'mcq', '["To maximise profit for the contractor", "To act in the client best interest", "To minimise costs regardless of quality", "To favour the contractor"]', 'B', 'The primary duty is to act in the client best interest.', 'easy', true),
('e0000001-0000-0000-0000-000000000001', 'nigerian_professional', 'QSRBN Registration Prep', 'Contract Administration', 'Which JCT contract is most suitable for major building projects?', 'mcq', '["Minor Works", "Intermediate", "Standard Building", "Design and Build"]', 'C', 'The JCT Standard Building Contract is for major building projects.', 'medium', true)

ON CONFLICT DO NOTHING;

-- NIQS Probation Exam questions
INSERT INTO exam_questions (exam_id, exam_category, exam_name, topic, question_text, question_type, options, correct_answer, explanation, difficulty, is_active) VALUES
('e0000001-0000-0000-0000-000000000002', 'nigerian_professional', 'NIQS Probation Exam', 'Measurement', 'Under SMM7, which rule covers the measurement of concrete works?', 'mcq', '["Rule 1", "Rule 2", "Rule 3", "Rule 4"]', 'C', 'Rule 3 covers concrete works measurement in SMM7.', 'medium', true),
('e0000001-0000-0000-0000-000000000002', 'nigerian_professional', 'NIQS Probation Exam', 'Measurement', 'NRM2 stands for which of the following?', 'mcq', '["National Rules of Measurement 2", "New Rules of Measurement 2", "Nigerian Rules of Measurement 2", "Standard Rules of Measurement 2"]', 'B', 'NRM2 is the New Rules of Measurement 2, published by RICS.', 'easy', true),
('e0000001-0000-0000-0000-000000000002', 'nigerian_professional', 'NIQS Probation Exam', 'Cost Planning', 'What is the primary purpose of an elemental cost plan?', 'mcq', '["To set the final contract sum", "To establish and control the budget", "To price the bill of quantities", "To settle final account disputes"]', 'B', 'The primary purpose is to establish and control the project budget.', 'easy', true),
('e0000001-0000-0000-0000-000000000002', 'nigerian_professional', 'NIQS Probation Exam', 'BOQ', 'What is a provisional sum in a BOQ?', 'mcq', '["A fixed price for defined work", "An estimate for work not yet defined", "A sum for contingencies only", "A daywork rate"]', 'B', 'A provisional sum is an estimate for work not yet fully defined.', 'medium', true),
('e0000001-0000-0000-0000-000000000002', 'nigerian_professional', 'NIQS Probation Exam', 'Contracts', 'Which FIDIC contract is known as the Red Book?', 'mcq', '["Conditions of Contract for Construction", "Conditions for Plant and Design-Build", "Conditions for EPC/Turnkey", "Short Form of Contract"]', 'A', 'The FIDIC Red Book is the Conditions of Contract for Construction.', 'medium', true)

ON CONFLICT DO NOTHING;

-- NIQS Intermediate Exam questions
INSERT INTO exam_questions (exam_id, exam_category, exam_name, topic, question_text, question_type, options, correct_answer, explanation, difficulty, is_active) VALUES
('e0000001-0000-0000-0000-000000000003', 'nigerian_professional', 'NIQS Intermediate Exam', 'Advanced Measurement', 'In NRM2, what is the minimum area for plastering to be measured separately?', 'mcq', '["0.5 m2", "1.0 m2", "1.5 m2", "2.0 m2"]', 'B', 'Under NRM2, plastering is measured separately above 1.0 m2.', 'medium', true),
('e0000001-0000-0000-0000-000000000003', 'nigerian_professional', 'NIQS Intermediate Exam', 'Cost Planning', 'What is value engineering in cost planning?', 'mcq', '["Reducing quality to cut costs", "Optimising the cost-to-value relationship", "Eliminating all contingencies", "Using cheaper contractors"]', 'B', 'Value engineering seeks the best value for money.', 'medium', true),
('e0000001-0000-0000-0000-000000000003', 'nigerian_professional', 'NIQS Intermediate Exam', 'Project Management', 'What is the purpose of a performance bond?', 'mcq', '["To cover defects", "To guarantee the contractor performance", "To pay for variations", "To cover insurance"]', 'B', 'A performance bond guarantees the contractor performance.', 'medium', true),
('e0000001-0000-0000-0000-000000000003', 'nigerian_professional', 'NIQS Intermediate Exam', 'Contractual Procedures', 'What is a compensation event under NEC?', 'mcq', '["A variation to the works", "An event entitling the contractor to additional time or money", "A defect in the works", "A delay caused by the contractor"]', 'B', 'A compensation event entitles the contractor to additional time or money.', 'medium', true),
('e0000001-0000-0000-0000-000000000003', 'nigerian_professional', 'NIQS Intermediate Exam', 'Construction Economics', 'What is whole life costing?', 'mcq', '["Costing the construction phase only", "Considering costs over the entire building life cycle", "Calculating the contractor total costs", "Estimating maintenance costs only"]', 'B', 'Whole life costing considers all costs over the entire building life cycle.', 'medium', true)

ON CONFLICT DO NOTHING;

-- RICS APC questions
INSERT INTO exam_questions (exam_id, exam_category, exam_name, topic, question_text, question_type, options, correct_answer, explanation, difficulty, is_active) VALUES
('e0000001-0000-0000-0000-000000000011', 'international', 'RICS APC - QS & Construction', 'Professionalism', 'What is the RICS Rules of Conduct?', 'mcq', '["A set of guidelines for client care", "Mandatory rules governing member behaviour", "A suggestion for best practice", "A legal requirement only"]', 'B', 'The RICS Rules of Conduct are mandatory rules governing member behaviour.', 'easy', true),
('e0000001-0000-0000-0000-000000000011', 'international', 'RICS APC - QS & Construction', 'Quantity Surveying', 'What is NRM1 used for?', 'mcq', '["Measuring building works", "Order of cost estimating and cost planning", "Civil engineering measurement", "Mechanical services measurement"]', 'B', 'NRM1 is used for order of cost estimating and cost planning.', 'easy', true),
('e0000001-0000-0000-0000-000000000011', 'international', 'RICS APC - QS & Construction', 'Cost Management', 'What is the purpose of a cost limit?', 'mcq', '["To set the minimum expenditure", "To set the maximum budget that cannot be exceeded", "To calculate the final account", "To estimate the contractor overhead"]', 'B', 'A cost limit sets the maximum budget that cannot be exceeded.', 'easy', true),
('e0000001-0000-0000-0000-000000000011', 'international', 'RICS APC - QS & Construction', 'Contract Administration', 'What is the role of the contract administrator?', 'mcq', '["To design the building", "To administer the contract on behalf of the employer", "To construct the building", "To finance the project"]', 'B', 'The contract administrator administers the contract for the employer.', 'easy', true),
('e0000001-0000-0000-0000-000000000011', 'international', 'RICS APC - QS & Construction', 'Property', 'What is property valuation in quantity surveying?', 'mcq', '["Only assessing building condition", "Determining the monetary value of a property", "Only measuring building dimensions", "Only assessing land quality"]', 'B', 'Property valuation determines the monetary value of a property.', 'easy', true)

ON CONFLICT DO NOTHING;

-- CIOB Chartered Membership questions
INSERT INTO exam_questions (exam_id, exam_category, exam_name, topic, question_text, question_type, options, correct_answer, explanation, difficulty, is_active) VALUES
('e0000001-0000-0000-0000-000000000012', 'international', 'CIOB Chartered Membership', 'Construction Management', 'What is the primary role of a construction manager?', 'mcq', '["To design the building", "To plan, coordinate and control construction projects", "To provide financing", "To obtain planning permission"]', 'B', 'The construction manager plans, coordinates and controls construction projects.', 'easy', true),
('e0000001-0000-0000-0000-000000000012', 'international', 'CIOB Chartered Membership', 'Building Technology', 'What is the purpose of a method statement?', 'mcq', '["To price the bill of quantities", "To describe how work will be carried out safely", "To calculate project costs", "To design the building structure"]', 'B', 'A method statement describes how work will be carried out safely.', 'easy', true),
('e0000001-0000-0000-0000-000000000012', 'international', 'CIOB Chartered Membership', 'Health & Safety', 'What is a risk assessment in construction?', 'mcq', '["A cost estimation exercise", "A systematic examination of workplace hazards", "A quality control procedure", "A project scheduling tool"]', 'B', 'A risk assessment is a systematic examination of workplace hazards.', 'easy', true),
('e0000001-0000-0000-0000-000000000012', 'international', 'CIOB Chartered Membership', 'Sustainability', 'What is BREEAM in construction?', 'mcq', '["A type of building material", "Building Research Establishment Environmental Assessment Method", "A construction contract form", "A project management tool"]', 'B', 'BREEAM is the Building Research Establishment Environmental Assessment Method.', 'medium', true),
('e0000001-0000-0000-0000-000000000012', 'international', 'CIOB Chartered Membership', 'Leadership', 'What is stakeholder management in construction?', 'mcq', '["Managing the construction workforce only", "Identifying and engaging all parties affected by the project", "Managing the project budget only", "Managing material procurement"]', 'B', 'Stakeholder management identifies and engages all parties affected by the project.', 'medium', true)

ON CONFLICT DO NOTHING;

-- PMP Certification questions
INSERT INTO exam_questions (exam_id, exam_category, exam_name, topic, question_text, question_type, options, correct_answer, explanation, difficulty, is_active) VALUES
('e0000001-0000-0000-0000-000000000013', 'international', 'PMP Certification', 'People', 'What is servant leadership in project management?', 'mcq', '["A leadership style focused on serving the team", "A hierarchical management approach", "A cost-cutting strategy", "A risk avoidance technique"]', 'A', 'Servant leadership focuses on supporting and empowering the team.', 'medium', true),
('e0000001-0000-0000-0000-000000000013', 'international', 'PMP Certification', 'Process', 'What is the critical path method (CPM)?', 'mcq', '["A cost estimation technique", "A scheduling method to determine the longest path of planned activities", "A quality control process", "A risk assessment tool"]', 'B', 'CPM determines the longest path of planned activities to measure project duration.', 'medium', true),
('e0000001-0000-0000-0000-000000000013', 'international', 'PMP Certification', 'Process', 'What is earned value management (EVM)?', 'mcq', '["A technique for measuring project performance and progress", "A method for calculating profit margins", "A quality assurance process", "A resource allocation tool"]', 'A', 'EVM measures project performance and progress against the baseline.', 'medium', true),
('e0000001-0000-0000-0000-000000000013', 'international', 'PMP Certification', 'Business Environment', 'What is a benefits realization plan?', 'mcq', '["A plan to maximise project costs", "A plan to ensure project delivers intended business value", "A plan to reduce project timeline", "A plan to minimise stakeholder engagement"]', 'B', 'A benefits realization plan ensures the project delivers intended business value.', 'medium', true),
('e0000001-0000-0000-0000-000000000013', 'international', 'PMP Certification', 'Process', 'What is a work breakdown structure (WBS)?', 'mcq', '["A cost estimation document", "A hierarchical decomposition of project deliverables", "A project schedule", "A risk register"]', 'B', 'A WBS is a hierarchical decomposition of the total scope of work.', 'easy', true)

ON CONFLICT DO NOTHING;

-- PRINCE2 Foundation questions
INSERT INTO exam_questions (exam_id, exam_category, exam_name, topic, question_text, question_type, options, correct_answer, explanation, difficulty, is_active) VALUES
('e0000001-0000-0000-0000-000000000014', 'international', 'PRINCE2 Foundation', 'Principles', 'How many principles does PRINCE2 have?', 'mcq', '["5", "6", "7", "8"]', 'C', 'PRINCE2 has 7 principles that underpin the methodology.', 'easy', true),
('e0000001-0000-0000-0000-000000000014', 'international', 'PRINCE2 Foundation', 'Themes', 'What is the purpose of the Business Case theme?', 'mcq', '["To manage project finances only", "To establish mechanisms to judge if the project is desirable, viable and achievable", "To control project scope only", "To manage project risks only"]', 'B', 'The Business Case theme establishes mechanisms to judge if the project is desirable, viable and achievable.', 'medium', true),
('e0000001-0000-0000-0000-000000000014', 'international', 'PRINCE2 Foundation', 'Processes', 'When does the Starting Up a Project process occur?', 'mcq', '["After project closure", "Before the project is formally initiated", "During project execution", "After planning is complete"]', 'B', 'Starting Up a Project occurs before the project is formally initiated.', 'easy', true),
('e0000001-0000-0000-0000-000000000014', 'international', 'PRINCE2 Foundation', 'Roles', 'Who is ultimately accountable for the project in PRINCE2?', 'mcq', '["Project Manager", "Team Manager", "Project Board", "Executive"]', 'C', 'The Project Board is ultimately accountable for the project.', 'medium', true),
('e0000001-0000-0000-0000-000000000014', 'international', 'PRINCE2 Foundation', 'Tailoring', 'What does tailoring mean in PRINCE2?', 'mcq', '["Ignoring project controls", "Adapting PRINCE2 to suit the project environment", "Using all PRINCE2 processes without change", "Reducing project team size"]', 'B', 'Tailoring means adapting PRINCE2 to suit the project environment.', 'easy', true)

ON CONFLICT DO NOTHING;

-- PRINCE2 Practitioner questions
INSERT INTO exam_questions (exam_id, exam_category, exam_name, topic, question_text, question_type, options, correct_answer, explanation, difficulty, is_active) VALUES
('e0000001-0000-0000-0000-000000000015', 'international', 'PRINCE2 Practitioner', 'Application', 'A project is experiencing scope creep. Which PRINCE2 principle should the Project Manager apply?', 'mcq', '["Continue regardless", "Manage by stages", "Learn from experience", "Focus on products"]', 'B', 'Managing by stages allows the Project Board to review and approve continued investment.', 'medium', true),
('e0000001-0000-0000-0000-000000000015', 'international', 'PRINCE2 Practitioner', 'Application', 'The Project Board wants to reduce the budget by 20% without changing scope. What should the Project Manager do?', 'mcq', '["Accept the budget cut", "Raise an issue with the Project Board about feasibility", "Reduce quality to cut costs", "Ignore the budget constraint"]', 'B', 'The Project Manager should raise an issue about feasibility as this may affect the Business Case.', 'medium', true),
('e0000001-0000-0000-0000-000000000015', 'international', 'PRINCE2 Practitioner', 'Application', 'A team member reports a risk that could delay the project by 2 weeks. What should the Project Manager do?', 'mcq', '["Ignore the risk", "Log the risk and assess its impact on tolerances", "Immediately inform the Project Board", "Escalate to the corporate management"]', 'B', 'The Project Manager should log the risk and assess its impact on tolerances.', 'medium', true),
('e0000001-0000-0000-0000-000000000015', 'international', 'PRINCE2 Practitioner', 'Application', 'Which document defines what the project will deliver and why?', 'mcq', '["Project Plan", "Business Case", "Project Brief", "Highlight Report"]', 'B', 'The Business Case defines what the project will deliver and why.', 'easy', true),
('e0000001-0000-0000-0000-000000000015', 'international', 'PRINCE2 Practitioner', 'Application', 'What is the purpose of a Lessons Learned report in PRINCE2?', 'mcq', '["To blame team members for mistakes", "To capture knowledge for future projects", "To close the project formally", "To update the Business Case"]', 'B', 'Lessons Learned reports capture knowledge for future projects.', 'easy', true)

ON CONFLICT DO NOTHING;

-- Job Interview Prep questions
INSERT INTO exam_questions (exam_id, exam_category, exam_name, topic, question_text, question_type, options, correct_answer, explanation, difficulty, is_active) VALUES
('e0000001-0000-0000-0000-000000000007', 'nigerian_professional', 'Job Interview Prep', 'Technical Knowledge', 'What is the difference between a bill of quantities and a schedule of rates?', 'mcq', '["There is no difference", "A BOQ has measured quantities; a schedule of rates has unit prices only", "A schedule of rates is more detailed", "A BOQ is used for international projects only"]', 'B', 'A BOQ has measured quantities while a schedule of rates has unit prices only.', 'medium', true),
('e0000001-0000-0000-0000-000000000007', 'nigerian_professional', 'Job Interview Prep', 'Situational Judgment', 'A client asks you to reduce costs by 15% on an ongoing project. What is the best approach?', 'mcq', '["Cut all contingencies", "Propose value engineering alternatives that maintain quality", "Reduce the project scope without consultation", "Suggest using cheaper materials"]', 'B', 'Value engineering alternatives maintain quality while reducing costs.', 'medium', true),
('e0000001-0000-0000-0000-000000000007', 'nigerian_professional', 'Job Interview Prep', 'Industry Knowledge', 'What is the role of a quantity surveyor in a construction project?', 'mcq', '["To design the building", "To manage costs, contracts, and financial aspects", "To supervise construction workers", "To obtain planning permission"]', 'B', 'A QS manages costs, contracts, and financial aspects of construction projects.', 'easy', true),
('e0000001-0000-0000-0000-000000000007', 'nigerian_professional', 'Job Interview Prep', 'Soft Skills', 'How do you handle a disagreement with a contractor over a variation?', 'mcq', '["Ignore the disagreement", "Review contract terms and negotiate fairly based on evidence", "Side with the contractor automatically", "Escalate immediately to the client"]', 'B', 'Reviewing contract terms and negotiating fairly based on evidence is the professional approach.', 'medium', true),
('e0000001-0000-0000-0000-000000000007', 'nigerian_professional', 'Job Interview Prep', 'CV & Portfolio', 'Which is most important when presenting a QS portfolio to an employer?', 'mcq', '["The number of projects listed", "Demonstrating measurable impact and specific skills", "The length of the document", "Including personal photographs"]', 'B', 'Demonstrating measurable impact and specific skills is most important.', 'easy', true)

ON CONFLICT DO NOTHING;

-- NIQS GDE questions
INSERT INTO exam_questions (exam_id, exam_category, exam_name, topic, question_text, question_type, options, correct_answer, explanation, difficulty, is_active) VALUES
('e0000001-0000-0000-0000-000000000004', 'nigerian_professional', 'NIQS GDE - Graduateship', 'Measurement', 'What is a comprehensive rate in BOQ pricing?', 'mcq', '["A rate that includes all costs for an item", "A rate for preliminary items only", "A rate that excludes materials", "A rate for labour only"]', 'A', 'A comprehensive rate includes all costs for an item.', 'medium', true),
('e0000001-0000-0000-0000-000000000004', 'nigerian_professional', 'NIQS GDE - Graduateship', 'Cost Planning', 'What is a cost model used for?', 'mcq', '["Predict future construction costs", "Set the contractor profit margin", "Determine material quantities", "Calculate VAT on projects"]', 'A', 'A cost model predicts future construction costs.', 'medium', true),
('e0000001-0000-0000-0000-000000000004', 'nigerian_professional', 'NIQS GDE - Graduateship', 'BOQ', 'Which section of a BOQ contains daywork rates?', 'mcq', '["Measured works", "Preliminaries", "Provisional sums", "Daywork schedule"]', 'D', 'Daywork rates are in a separate daywork schedule.', 'medium', true),
('e0000001-0000-0000-0000-000000000004', 'nigerian_professional', 'NIQS GDE - Graduateship', 'Contracts', 'What is the purpose of a performance bond?', 'mcq', '["To cover defects", "To guarantee the contractor performance", "To pay for variations", "To cover insurance"]', 'B', 'A performance bond guarantees the contractor performance.', 'medium', true),
('e0000001-0000-0000-0000-000000000004', 'nigerian_professional', 'NIQS GDE - Graduateship', 'Professional Practice', 'What is continuing professional development (CPD)?', 'mcq', '["Working overtime on projects", "Ongoing learning to maintain professional competence", "Developing new building designs", "Managing project risks"]', 'B', 'CPD is ongoing learning to maintain professional competence.', 'easy', true)

ON CONFLICT DO NOTHING;

-- NIQS TPC questions
INSERT INTO exam_questions (exam_id, exam_category, exam_name, topic, question_text, question_type, options, correct_answer, explanation, difficulty, is_active) VALUES
('e0000001-0000-0000-0000-000000000005', 'nigerian_professional', 'NIQS TPC - Test of Professional Competence', 'Measurement', 'What is the squaring of dimensions in taking-off?', 'mcq', '["Multiplying width by length by height", "Adding all dimensions together", "Measuring in square metres only", "Calculating volumes only"]', 'A', 'Squaring involves multiplying three dimensions.', 'easy', true),
('e0000001-0000-0000-0000-000000000005', 'nigerian_professional', 'NIQS TPC - Test of Professional Competence', 'Cost Planning', 'What is the correct order of cost planning stages?', 'mcq', '["Cost plan, Cost estimate, Cost limit, Cost check", "Cost estimate, Cost limit, Cost plan, Cost check", "Cost limit, Cost estimate, Cost plan, Cost check", "Cost check, Cost plan, Cost limit, Cost estimate"]', 'B', 'The correct order is: Cost estimate, Cost limit, Cost plan, Cost check.', 'medium', true),
('e0000001-0000-0000-0000-000000000005', 'nigerian_professional', 'NIQS TPC - Test of Professional Competence', 'BOQ', 'What is a contractor risk item in a BOQ?', 'mcq', '["An item where the contractor bears quantity risk", "An item with provisional quantities", "An item for provisional sums", "An item measured in detail"]', 'A', 'A contractor risk item means the contractor bears quantity risk.', 'hard', true),
('e0000001-0000-0000-0000-000000000005', 'nigerian_professional', 'NIQS TPC - Test of Professional Competence', 'Contracts', 'What is the purpose of a delay damages clause?', 'mcq', '["To cover contractor profit", "To compensate the employer for delay", "To pay for variations", "To cover insurance costs"]', 'B', 'A delay damages clause compensates the employer for delay.', 'medium', true),
('e0000001-0000-0000-0000-000000000005', 'nigerian_professional', 'NIQS TPC - Test of Professional Competence', 'Professional Practice', 'What is the primary duty of a QS to their client?', 'mcq', '["To maximise profit for the contractor", "To act in the client best interest", "To minimise costs regardless of quality", "To favour the contractor"]', 'B', 'The primary duty is to act in the client best interest.', 'easy', true)

ON CONFLICT DO NOTHING;

-- NIQS PCI questions
INSERT INTO exam_questions (exam_id, exam_category, exam_name, topic, question_text, question_type, options, correct_answer, explanation, difficulty, is_active) VALUES
('e0000001-0000-0000-0000-000000000006', 'nigerian_professional', 'NIQS PCI Prep', 'Professional Interview Technique', 'How should you respond when asked about a project failure in an interview?', 'mcq', '["Deny any involvement", "Describe the situation, what you learned, and how you applied it", "Blame other team members", "Refuse to answer the question"]', 'B', 'Describing what you learned and how you applied it demonstrates professional growth.', 'medium', true),
('e0000001-0000-0000-0000-000000000006', 'nigerian_professional', 'NIQS PCI Prep', 'Case Study Presentation', 'When presenting a cost plan to a client, what is most important?', 'mcq', '["Using complex terminology", "Clear communication of costs, risks, and recommendations", "Presenting the cheapest option only", "Avoiding questions about contingencies"]', 'B', 'Clear communication of costs, risks, and recommendations is essential.', 'medium', true),
('e0000001-0000-0000-0000-000000000006', 'nigerian_professional', 'NIQS PCI Prep', 'Ethical Scenarios', 'A contractor offers you a gift after winning a bid. What should you do?', 'mcq', '["Accept the gift", "Decline and report it according to your code of conduct", "Accept but keep it secret", "Ask for a cash equivalent instead"]', 'B', 'Declining and reporting is the ethical response under professional codes of conduct.', 'easy', true),
('e0000001-0000-0000-0000-000000000006', 'nigerian_professional', 'NIQS PCI Prep', 'Client Communication', 'How do you explain a cost overrun to a client?', 'mcq', '["Minimise the issue", "Provide transparent analysis with corrective action plans", "Blame the contractor", "Avoid the topic until asked"]', 'B', 'Transparent analysis with corrective action plans demonstrates professionalism.', 'medium', true),
('e0000001-0000-0000-0000-000000000006', 'nigerian_professional', 'NIQS PCI Prep', 'Team Leadership', 'How do you handle underperforming team members?', 'mcq', '["Ignore the issue", "Provide constructive feedback and support for improvement", "Report immediately to HR", "Assign all their work to others"]', 'B', 'Providing constructive feedback and support demonstrates effective leadership.', 'medium', true)

ON CONFLICT DO NOTHING;

COMMENT ON COLUMN exam_definitions.slug IS 'URL-friendly identifier for professional exams (e.g., qsrbn-registration, niqs-probation)';
